cs/src/io/unsafe/StreamCloning.cs

Mono MemoryStream internal implementation differs from .NET implementation
It does not have `InternalGetOriginAndLength` method. So the cloning
method changed to use mono implementation of MemoryStream
when the method `InternalGetOriginAndLength` is not found
This commit fixes `NullReferenceException` when running unit tests on mono

Fix clone of MemoryStream on Mono

---

examples/cs/comm/logging/logging.csproj
examples/cs/comm/notifyevent/notifyevent.csproj
examples/cs/comm/pingpong/pingpong.csproj

* Remove unneeded references to Bond.IO.dll
* Remove unneeded system references

[comm] Simplify example MSBuild files

---

README.md

Update README to use VS2015 instead of VS2013.

Update README to use VS2015 instead of VS2013

---

README.md

Follow up to pull request https://github.com/Microsoft/bond/pull/206
Boost would need to be updated to 14 to fit with the recent changes of using VS2015

Update Boost readme example

---

cs/cs.sln
cs/test/compat/comm/client/CommCompatClient.csproj
cs/test/compat/comm/server/CommCompatServer.csproj
cs/test/compat/comm/shared/CommCompatShared.csproj

* Fixed assembly references in C# comm compat tests
* Fixed debug/release mismatch in cs.sln's Fields configuration
Note to reviewer/merged: please rebase these commits atop master (do not squash or merge)

Fix C# build on Mono

---

examples/cs/comm/tls/Tls.cs

Before, we were only listening on IPv4 loopback. If "localhost" resolves
to [::1], we couldn't connect. Now, we listen on both of the default
IPv4 and IPv6 loopback addresses.

[c# epoxy] Fix TLS example for IPv6 localhost

---

examples/cpp/comm/error/CMakeLists.txt
examples/cpp/comm/event/CMakeLists.txt

Fix a regression from https://github.com/Microsoft/bond/pull/323

[C++ Comm] Fix cmake problems in examples

---

.travis.yml

[travis] Install Cabal library

---

cpp/inc/bond/core/nullable.h
cpp/inc/bond/core/stl_containers.h
cpp/inc/bond/core/traits.h
cpp/inc/bond/stream/output_buffer.h

Support C++11 and above allocator model for rebind

---

cs/build/internal/Common.Internal.targets

Fixes issues with Mono build on Travis.

Address issue with Mono .mdb -> .pdb change

---

cs/test/compat/grpc/client/Program.cs
cs/test/compat/grpc/server/Program.cs
examples/cs/grpc/pingpong/GrpcPingPong.cs

- replace localhost with 127.0.0.1

[grpc c#] Remove use of localhost in example

---

compiler/Main.hs
doc/CMakeLists.txt

- Show all gbc options in documentation
- When running gbc without options show full help

[doc] Output all gbc options

---

README.md

- readme was not showing the correct badge
- appveyor badge api change

[doc] Fix appveyor badge

---

cpp/test/compat/grpc/pingpong_client.cpp
cpp/test/compat/grpc/pingpong_server.cpp
cs/test/compat/grpc/client/Program.cs
cs/test/compat/grpc/server/Program.cs
test/compat/grpc/pingpong.bond

Test event support in gRPC compatibility tests for C++ and C#.

[gRPC] Add events to gRPC compat tests

---

compiler/src/Language/Bond/Codegen/Java/Enum_java.hs
java/core/src/main/java/com/microsoft/bond/BondEnum.java

Changes:
- added BondEnum interface that all all generated enum classes implement
- enums implement the contract of the Compable interface
- toString method returns the enum constant label if it exists

Java: made generated enum classes implement interfaces and updated toString

---

compiler/Main.hs
compiler/Options.hs
compiler/tests/Main.hs
compiler/tests/Tests/Codegen.hs
compiler/tests/generated/attributes_concatenated.java
compiler/tests/generated/basic_types_concatenated.java
compiler/tests/generated/complex_types_concatenated.java
compiler/tests/generated/defaults_concatenated.java
compiler/tests/generated/field_modifiers_concatenated.java
compiler/tests/generated/generics_concatenated.java
compiler/tests/generated/inheritance_concatenated.java

Meta and alias don't work due to not being implemented in this version of Java codegen.

java: Add golden tests.

---

appveyor.yml
cs/build/nuget/Common.targets

- Correctly find the just compiled gbc
- Add fail condition to appveyor CI
- Closes https://github.com/Microsoft/bond/issues/526

[msbuild] Find gbc in a clean build

---

java/core/src/test/java/com/microsoft/bond/protocol/StringHelperTest.java
java/core/src/test/java/com/microsoft/bond/protocol/TaggedBinaryTestHelper.java

Replaced non-ASCII characters in source files with Unicode escape sequences.

[Java] Fixed build errors caused by UFT-8 encoding of source files.

---

java/core/src/main/java/com/microsoft/bond/Bonded.java
java/core/src/test/bond/bonded.bond
java/core/src/test/bond/common.bond
java/core/src/test/bond/equality.bond
java/core/src/test/java/com/microsoft/bond/BondedTest.java
java/core/src/test/java/com/microsoft/bond/codegen/EqualsHashCodeTests.java

Also refactored Java core's test bondfiles a little.

java core: Add Bonded.cast().

---

ThirdPartyNotices.txt

Adds appropriate attribution for gRPC and libraries used within gRPC.

Update third-party notices with gRPC and more

---

cpp/inc/bond/protocol/detail/simple_array.h
cpp/test/core/checked_add_test.cpp

Also, extend checked_add tests.

[C++] Additional security fixes in SimpleArray

---

cs/src/core/expressions/ObjectParser.cs
cs/test/core/ConvertTests.cs
cs/test/expressions/DeserializeCB.expressions
cs/test/expressions/DeserializeJson.expressions
cs/test/expressions/DeserializeSP.expressions
cs/test/expressions/DeserializeXml.expressions
cs/test/expressions/SerializeCB.expressions
cs/test/expressions/SerializeSP.expressions
cs/test/expressions/SerializeXml.expressions
cs/test/expressions/TranscodeCBSP.expressions
cs/test/expressions/TranscodeSPCB.expressions
cs/test/expressions/schemas.bond

- Fixes issue https://github.com/Microsoft/bond/issues/660

[c#] Fix alias missing convert

---

tools/image-builder/build_bond.zsh

This fixes the bug introduced in #681.

[build] Fix broken build on gcc

---

.travis.yml

Cache takes longer than 3 minutes to upload https://travis-ci.org/Microsoft/bond/jobs/295485207#L1366

[travis] Increase cache upload time-out

---

CHANGELOG.md
compiler/src/Language/Bond/Parser.hs
compiler/tests/schema/service.bond

* add optional semi colon after an import statement

[gbc] Improve parsing of import statements

---

README.md
doc/src/bond_cpp.md
doc/src/bond_cs.md
doc/src/bond_java.md
doc/src/bond_py.md
java/core/src/main/java/org/bondlib/CompactBinaryReader.java

(plus renaming a couple locals)

Add Java documentation.

---

doc/CMakeLists.txt
doc/src/bond_cpp.md
doc/src/bond_cs.md
doc/src/bond_java.md

Generate Java docs properly + add gradle plugin docs.

---

.gitmodules

Fix whitespace in .gitmodules

---

cpp/inc/bond/protocol/detail/simple_array.h

Resolves https://github.com/Microsoft/bond/issues/786

cpp: #include <new> for std::bad_alloc.

---

.gitattributes

Various .gitattributes fixes

---

CHANGELOG.md
cs/dnc/src/grpc/project.json
cs/nuget/bond.grpc.csharp.nuspec
cs/src/grpc/grpc.csproj
cs/src/grpc/packages.config
cs/test/compat/grpc/client/GrpcCompatClient.csproj
cs/test/compat/grpc/client/packages.config
cs/test/compat/grpc/server/GrpcCompatServer.csproj
cs/test/compat/grpc/server/packages.config
cs/test/compat/grpc/shared/GrpcCompatShared.csproj
cs/test/compat/grpc/shared/packages.config
cs/test/grpc/grpc.csproj
cs/test/grpc/packages.config
examples/cs/grpc/pingpong/grpc_pingpong.csproj
examples/cs/grpc/pingpong/packages.config
examples/cs/grpc/scalar/grpc_scalar.csproj
examples/cs/grpc/scalar/packages.config
examples/cs/grpc/shared-types-assembly/client/grpc_sta-client.csproj
examples/cs/grpc/shared-types-assembly/client/packages.config
examples/cs/grpc/shared-types-assembly/server/grpc_sta-server.csproj
examples/cs/grpc/shared-types-assembly/server/packages.config

Fixes https://github.com/Microsoft/bond/issues/812

[c# grpc] Upgrade to gRPC v1.10.0

---

.travis.yml

This uses an image built on 2018-03-22.

[travis] Refresh Travis CI image

---

CHANGELOG.md
cpp/inc/bond/core/config.h
cpp/inc/bond/core/detail/mpl.h
cpp/inc/bond/core/detail/omit_default.h
cpp/inc/bond/core/reflection.h
cpp/inc/bond/core/traits.h
cpp/inc/bond/protocol/encoding.h

[c++] Replace bond::check_method with decltype

---

CHANGELOG.md
cs/src/core/expressions/ObjectParser.cs
cs/src/core/expressions/TypeAlias.cs
cs/test/core/SerializationTests.cs
cs/test/core/UnitTest.bond
cs/test/expressions/Clone.expressions
cs/test/expressions/DeserializeCB.expressions
cs/test/expressions/DeserializeJson.expressions
cs/test/expressions/DeserializeSP.expressions
cs/test/expressions/DeserializeXml.expressions
cs/test/expressions/Expressions.csproj
cs/test/expressions/Program.cs
cs/test/expressions/SerializeCB.expressions
cs/test/expressions/SerializeSP.expressions
cs/test/expressions/SerializeXml.expressions
cs/test/expressions/TranscodeCBSP.expressions
cs/test/expressions/TranscodeSPCB.expressions
cs/test/expressions/schemas.bond

[c#] Fix alias conversion issue for generic field

---

.travis.yml

Use the image built from commit fdfc1276d2953727005a68c02d37bd42f96962b8

Refresh Travis CI image

---

appveyor.yml

- Install GHC
- Use cabal to install Happy
This is to fix https://github.com/microsoft/bond/issues/989

[CI] Happy workaround

---

README.md

Just fixed grammar in ReadMe.md

Minor grammar fixes.

---

.travis.yml

This version of the builder image was build on 2020-07-14.

Update Travis build image

---

.github/workflows/linux_cron.yml
appveyor.yml

[ci] update image for cron run

---

examples/cpp/core/move_semantics/move_semantics.cpp

Adds missing include of `<algorithm>` to fix build issue.

Adding missing include of algorithm

---

CHANGELOG.md
cpp/inc/bond/core/parser.h
cpp/test/core/merge_test.cpp
cpp/test/core/unit_test_core.bond

[c++] Fix DynamicParser's skipped OmittedField call
