compiler/CMakeLists.txt
On OS X at least, the CMake permissions don't leave the gbc compiler executable by the current user. OWNER and GROUP need to both be specified.
=> Fix compiler CMake permissions for OSX

README.md
The instructions for OS X are incomplete if you've got homebrew python installed. It turns out cmake + python + homebrew is a world of pain. This seems to be the simplest way to get the unit tests to pass.
Feel free to decline if you think it'd be better captured somewhere else.
=> Update OS X instruction for homebrew Python

cs/src/core/expressions/DeserializerTransform.cs, cs/src/core/expressions/ObjectParser.cs, cs/src/core/expressions/SerializerTransform.cs, cs/src/core/expressions/UntaggedParser.cs, cs/src/core/protocols/SimpleXmlWriter.cs, cs/test/core/Aliases.bond, cs/test/core/Core.csproj, cs/test/core/TypeAliasTests.cs, cs/test/expressions/TranscodeCBCB.expressions, cs/test/expressions/TranscodeCBSP.expressions
By default the blob type maps in C# to ArraySegment<byte>. This choice
is dictated by performance: using ArraySegment rather than a simple
array allows deserializer to avoid memcpy.
At the same time arrays are often a very convenient type in C# and Bond
supports T[] as an alternative mapping for the schema type vector<T>.
Although C# codegen doesn't generate arrays by default, users can either
manually annotate array fields in their own classes with Bond attributes
or they can use custom type alias mapping support (the gbc command line
option --using) to generate classes with array fields.
This change optimizes how C# byte[] is handled by object parser as well
as serializer and deserializer transforms. Instead of reading/writing
each byte individually, which is very expensive, when …
=> Optimize C# byte[]

cs/build/Bond.CSharp.targets, cs/test/core/Core.csproj, cs/test/core/UnitTest.bond, cs/test/expressions/Expressions.csproj, cs/test/expressions/schemas.bond
This is the second step of making solution compilable with xbuild.
It resolves all xbuild compilation issues except using references
to VisualStudio asseblies in test projects.
Fixed:
- wrong path dilimiter usage in bond files on linux system
- different case-sensitivity in file names
- passing global $(BondOptions) property to codegen process
=> Make test and examples projects are compilable with xbuild

cpp/inc/bond/protocol/encoding.h
Found an issue with possible underflow in functions ReadStringData and WriteStringData.
=> Remove possible underflow in string buffer encoder

cpp/inc/bond/core/blob.h, cpp/inc/bond/core/bonded.h, cpp/inc/bond/core/bonded_void.h, cpp/inc/bond/core/container_interface.h, cpp/inc/bond/core/detail/inheritance.h, cpp/inc/bond/core/detail/protocol_visitors.h, cpp/inc/bond/core/detail/tags.h, cpp/inc/bond/core/detail/typeid_value.h, cpp/inc/bond/core/nullable.h, cpp/inc/bond/core/protocol.h, cpp/inc/bond/core/reflection.h, cpp/inc/bond/core/schema.h, cpp/inc/bond/core/transforms.h, cpp/inc/bond/core/value.h, cpp/inc/bond/protocol/compact_binary.h, cpp/inc/bond/protocol/simple_binary.h, examples/cpp/core/protocol_versions/protocol_versions.cpp, python/inc/bond/python/converters.h, python/inc/bond/python/struct.h
I'm trying to use bond on an embedded platform, for which the compiler considers unnecessary semicolons to be unforgivable syntax errors. This commit removes all the unused semicolons I could find in the tree.
=> Remove unnecessary semicolons

cs/build/Bond.CSharp.targets, cs/test/core/Core.csproj
When support for import directories with spaces in their paths was
added, that inadvertently broke codegen when one ended with a trailing
slash. We add a trailing \. like we do for the output directory to fix
that.
=> Fix import directories with trailing slashes

cs/cs.sln, examples/cs/core/import/common/common.bond, examples/cs/core/import/common/protocol/header.bond, examples/cs/core/import/import.csproj, examples/cs/core/import/program.cs, examples/cs/core/import/schema.bond
This started off in a [pull request to add support for paths with spaces](https://github.com/Microsoft/bond/pull/29#discussion_r24217432) but has been split into its own request.
From the comments in that PR, we wanted the example to have a partial path. This one has that.
=> Add example showing how import can be used

cs/src/json/expressions/json/SimpleJsonParser.cs, cs/src/json/protocols/SimpleJsonReader.cs, cs/test/core/JsonParsingTests.cs, cs/test/core/UnitTest.bond
When reading string fields, the SimpleJsonParser expects to find a JsonToken of
type String. But if the string value matches a date format, the actual JsonToken
that is seen is of type Date. To fix this, we are setting the JsonTextReader to not
try to parse strings as dates.
Also improve the exception text when reading unenxpected input to help know
what JsonToken was actually read, and fix a similar possible issue with parsing
doubles.
=> Fix bug in JSON parsing when string value is a date

cpp/inc/bond/core/config.h, cpp/inc/bond/core/exception.h, cpp/inc/bond/core/protocol.h, cpp/inc/bond/protocol/compact_binary.h, cpp/inc/bond/protocol/fast_binary.h, cpp/inc/bond/protocol/simple_binary.h
This PR replaces the dynamic exception specifications that are deprecated in newer versions of the C++ standard with a macro that's configured by boost. 
This should hopefully preserve the optimizations in boost::variant, though I can't confirm first-hand if that's the case.
=> Replace dynamic exception specifications with portable boost config specifier

why_bond.html
Adds page title as "Why Bond?" and fixes typo "transform" to "transforms"
=> Adds title and fixes typo on Why Bond? page

cs/src/core/Clone.cs, cs/src/core/Deserializer.cs, cs/src/core/expressions/DeserializerTransform.cs
When the schemas dependency graph complexity increases, the expression
trees that are generated by the DeserializeTransform can become very
large, leading to long compilation times and high memory consumption.
This change adds some Deserializer constructors that support a flag to
disable expression inlining. As a result the runtime deserialization
operation will be slightly slower (with some added overhead of function
calls), but the initialization of the Deserializer is significantly
faster.
=> Add support for Deserializer without inlining

doc/src/bond_cs.md
Fix a minor type in the example code of CSharp documentation
Signed-off-by: Vineel Kumar Reddy Kovvuri <vineel.kovvuri@gmail.com>
=> Fix Typo in C# bond manual

python/inc/bond/python/converters.h, python/inc/bond/python/struct.h
- Define py_object_identity as static
- Inline register_builtin_converters for linker
- Fix typo of name register_builtin_converters
=> Allow split python struct defs across many files

cs/src/core/expressions/ObjectParser.cs, cs/test/expressions/SerializeCB.expressions, cs/test/expressions/SerializeSP.expressions, cs/test/expressions/SerializeXml.expressions
Reduce number of calls to BondTypeAliasConverter.Convert methods
for type-aliased blobs fields.
=> Optimize Serializer for type-aliased blob fields

cs/src/core/expressions/xml/SimpleXmlParser.cs, cs/test/core/XmlTests.cs, cs/test/expressions/DeserializeXml.expressions
Closes #112 
* SimpleXmlParser now handles XML declarations
* When SimpleXmlParser encounters an unexpected node type it report the type
* Improve XmlTests to test that SimpleXmlParser ignores comments itself
=> SimpleXmlParser handles XML declarations

cpp/inc/bond/core/config.h, cpp/inc/bond/core/nullable.h, cpp/inc/bond/protocol/random_protocol.h, cpp/inc/bond/protocol/simple_json_reader.h
Covers points 1, 2, 3, 4, and 6 that I raised in issue #167 as well as reduce two additional dynamic allocations.
=> Improvements and fixes for C++ nullable implementation and reduce dynamic allocation 

cs/src/comm/epoxy-transport/EpoxyListener.cs
We anticipate that sometimes we won't be able to accept a connection, so
such a case should be logged as a regular error instead of a fatal (so
take the process down) error.
=> Make accept failures in EpoxyListener non-fatal

doc/CMakeLists.txt
With the `--self-contained` flag to Pandoc, we were downloading the
NuGet version badges at build time and embedding them in the generated
HTML as data URIs. We actually want those to be fetched anew each time
someone renders the page so they see the latest version, not the version
that was current when the page was generated.
This should also get rid of the build failures we were seeing when
shields.io was down.
=> Don't download and embed images for C# docs

cpp/test/core/metadata_tests.cpp
* `int` changed to `std::size_t` when indexing STL containers
=> [c++] x86 build fixes

cs/src/comm/epoxy-transport/EpoxyTransport.cs, cs/test/comm/Epoxy/EpoxyTransportTests.cs
* Both listeners and connections can be made to IPv6 addresses now.
* Default resolver no longer prefers IPv4 addresses. It just uses the first
address returned.
=> [epoxy] Add IPv6 support

appveyor.yml, cmake/Config.cmake
- Use AppVeyor pre-installed Boost
- Run C++ unit tests
- Fail if Boot unit_test_framework is not found
=> Fix AppVeyor CI

compiler/src/Language/Bond/Codegen/Cpp/Types_h.hs, compiler/tests/generated/alias_key_types.h, compiler/tests/generated/alias_with_allocator_types.h, compiler/tests/generated/aliases_types.h, compiler/tests/generated/allocator/alias_key_types.h, compiler/tests/generated/allocator/aliases_types.h, compiler/tests/generated/allocator/attributes_types.h, compiler/tests/generated/allocator/basic_types_types.h, compiler/tests/generated/allocator/bond_meta_types.h, compiler/tests/generated/allocator/complex_types_types.h, compiler/tests/generated/allocator/defaults_types.h, compiler/tests/generated/allocator/field_modifiers_types.h, compiler/tests/generated/allocator/generics_types.h, compiler/tests/generated/allocator/inheritance_types.h, compiler/tests/generated/allocator/maybe_blob_types.h, compiler/tests/generated/attributes_types.h, compiler/tests/generated/basic_types_types.h, compiler/tests/generated/bond_meta_types.h, compiler/tests/generated/complex_types_types.h, compiler/tests/generated/custom_alias_with_allocator_types.h, compiler/tests/generated/custom_alias_without_allocator_types.h, compiler/tests/generated/defaults_types.h, compiler/tests/generated/field_modifiers_types.h, compiler/tests/generated/generics_types.h, compiler/tests/generated/inheritance_types.h, compiler/tests/generated/maybe_blob_types.h
This fixes another bit of invalid C++ generated when a bondfile contains a struct and an enum value with the same name.
Previously: #202, #204
=> [gbc] Fully qualify names in generated C++ swap()s.

cs/src/comm/epoxy-transport/EpoxyTransport.cs
Use `Uri.DnsSafeHost`, which can be configured at an application level
to return Punycode-encoded ACEs.
.NET 4.6 includes `Uri.IdnHost`, which is always Punycode-encoded if
needed, but Mono doesn't yet support that, so we can't use it.
=> [epoxy] Add basic IDN support to conn. strings

CHANGELOG.md, cs/src/comm/epoxy-transport/EpoxyConnection.cs, cs/src/comm/epoxy-transport/EpoxyContexts.cs, cs/src/comm/epoxy-transport/EpoxyListener.cs, cs/src/comm/epoxy-transport/EpoxyTransport.cs, cs/src/comm/interfaces/Connections.cs, cs/src/comm/interfaces/Contexts.cs, cs/src/comm/interfaces/Errors.cs, cs/src/comm/interfaces/ILayerStack.cs, cs/src/comm/interfaces/Listener.cs, cs/src/comm/interfaces/Metrics.cs, cs/src/comm/interfaces/Transport.cs, cs/src/comm/layers/LayerStack.cs, cs/src/comm/service/ServiceHost.cs, cs/src/comm/simpleinmem-transport/Processor/BatchProcessor.cs, cs/src/comm/simpleinmem-transport/SimpleInMemConnection.cs, cs/src/comm/simpleinmem-transport/SimpleInMemContexts.cs, cs/src/comm/simpleinmem-transport/SimpleInMemListener.cs, cs/src/comm/simpleinmem-transport/SimpleInMemTransport.cs, cs/test/comm/Interfaces/ErrorsTests.cs, cs/test/comm/Interfaces/ListenerTests.cs, cs/test/comm/Interfaces/LoggerTests.cs, cs/test/comm/Interfaces/MetricsTests.cs, cs/test/comm/Layers/LayerStackTests.cs
The internal consequences of this change are somewhat widespread. I've made RequestMetrics creation and emission the responsibility of Connections, rather than the ServiceHost, and I've added both flavors of metrics the base Context structure, with the immediate intent to make them visible to Layers.
This change also includes an end-to-end metrics test for requests and events. We still need a similar test to make sure valid metrics are emitted in various error cases, but this diff is uncomfortably large as it is.
=> [c#] Thread request IDs through to InternalServerErrors.

CHANGELOG.md, cs/nuget/bond.runtime.csharp.nuspec
- Bond can now be used with Newtonsoft.Json >= 7.0.1 and < 10
- Closes issue https://github.com/Microsoft/bond/issues/212
=> Relax the upper bound of Newtonsoft Json dependency

cs/test/comm/Interfaces/MetricsTests.cs, cs/test/comm/Interfaces/ServiceIsolationTests.cs
Previously, the tests were failing, but the failure exceptions were getting
swallowed by an async void function. Additionally, this increases the length of
the pause for metrics to settle.
=> [c#] Fix metrics tests.

cs/src/comm/interfaces/Errors.cs, cs/test/comm/Interfaces/ErrorsTests.cs, idl/bond/comm/comm.bond
Error now has a `nullable<bonded<Error>> inner_error` field. If multiple
errors need to be represented, the `AggregateError` struct and its error
code, `MultipleErrorsOccured`, can be used to collect these up.
=> [comm] Switch Error to only have one inner_error

cs/src/comm/epoxy-transport/EpoxyListener.cs
Cache the EpoxyListener endpoint information so that it can be accessed
after socket shutdown for things like logging.
This resolves a sporadic unit test failure.
Minor adjustments to match style guide for things like private and
readonly.
=> [epoxy] Cache listener endpoint for after shutdown

CHANGELOG.md, cs/src/comm/epoxy-transport/EpoxyConnection.cs, cs/src/comm/epoxy-transport/EpoxyProtocol.cs, cs/src/comm/epoxy-transport/Frame.cs, cs/src/comm/interfaces/Message.cs, cs/src/comm/simpleinmem-transport/Processor/BatchProcessor.cs, cs/src/comm/simpleinmem-transport/Processor/Util.cs, cs/src/comm/simpleinmem-transport/SimpleInMemConnection.cs, cs/src/comm/simpleinmem-transport/SimpleInMemTransport.bond, cs/test/comm/Epoxy/EpoxyProtocolTests.cs, cs/test/comm/Epoxy/FrameTests.cs, cs/test/comm/Interfaces/MessageTests.cs, doc/src/bond_comm_epoxy_wire.md, idl/bond/comm/comm.bond, idl/bond/comm/epoxy_transport.bond
Indicate transmission of an Error using a new framelet instead. In
addition, remove ErrorCode.OK and rename Epoxy's PayloadType to
EpoxyMessageType.
Left to do:
@chadwalters, @tstein: please review, as you've already seen some parts of this change elsewhere.
=> [c# comm] Remove error code from EpoxyHeaders

CHANGELOG.md, cs/nuget/bond.runtime.csharp.nuspec
The Bond.Runtime NuGet package again only specifies a lower bound on its
Newtonsoft.JSON dependency. This reverts commit
e2be0bf3ec12e97555cf6204dc56cb8b6a4985f4, which artificially limited the
upper bound to < 10. The previous behavior did not limit Bond.Runtime to
only working with Newtonsoft.Json 7.0.1. _However_, the default behavior
of NuGet (since 2.8) is to install the _lowest_ version of a package
that satisfied the constraints. This behavior can be overridden when a
package is installed, but that decision needs to be made by the consumer
of Bond.Runtime.
Closes https://github.com/Microsoft/bond/issues/212
=> Undo Bond.Runtime's limit to Newtonsoft.Json < 10

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cs/Comm_cs.hs, compiler/tests/generated/generic_service_proxies.cs, compiler/tests/generated/service_proxies.cs, cs/src/comm/epoxy-transport/EpoxyConnection.cs, cs/src/comm/epoxy-transport/EpoxyProtocol.cs, cs/src/comm/epoxy-transport/ResponseMap.cs, cs/src/comm/interfaces/Connections.cs, cs/src/comm/interfaces/Errors.cs, cs/src/comm/interfaces/Listener.cs, cs/src/comm/service/ServiceHost.cs, cs/src/comm/simpleinmem-transport/Processor/BatchProcessor.cs, cs/src/comm/simpleinmem-transport/SimpleInMemConnection.cs, cs/src/comm/simpleinmem-transport/SimpleInMemTransport.bond, cs/test/comm/Epoxy/EpoxyConnectionTests.cs, cs/test/comm/Epoxy/EpoxyProtocolTests.cs, cs/test/comm/Epoxy/EpoxyTestBase.cs, cs/test/comm/Epoxy/EpoxyTransportTests.cs, cs/test/comm/Epoxy/ResponseMapTests.cs, cs/test/comm/Interfaces/ErrorsTests.cs, cs/test/comm/Interfaces/MetricsTests.cs, cs/test/comm/Layers/LayerStackTests.cs, cs/test/comm/SimpleInMem/SimpleInMemConnectionTest.cs, cs/test/core/JsonParsingTests.cs, cs/test/core/XmlTests.cs, doc/src/bond_comm_epoxy_wire.md, examples/cs/comm/metrics/ConsoleMetricsSink.cs, idl/bond/comm/comm.bond, idl/bond/comm/epoxy_transport.bond
Conform to predominant IDL naming convention. Also pass service and method
names as separate strings. Minor fixups on empty string usage in C#.
=> [IDL Comm] Improve IDL for consistent naming

CMakeLists.txt, cmake/Config.cmake, examples/cpp/core/bf/CMakeLists.txt
Improves the Bond CMake build to make it easier to build the minimum amount needed to consume Bond in a C++ project.
* Improve logic to locate a pre-compiled gbc
* Add ability to request that just the libraries be built and no additional tools (like bf)
=> CMake improvements for stand-alone builds

examples/cpp/core/serialization/serialization.cpp, examples/cs/core/serialization/program.cs, examples/cs/core/serialization/schema.bond, examples/cs/core/serialization/serialization.csproj
Both examples now use the same schema and populate the object with the same
values.
=> Bring C++ and C# serialization examples in sync

cs/build/nuget/Common.targets
If all of the items in the BondCodegen ItemGroup had their Options
metadata set, codegen was always invoked, as the dummy output file
`bondfiles.tmp` was never generated.
Now, the dummy output file (renamed to `bondcodegen.done`) is always
output, and the batched input file has been renamed to
`bonddefaultcodegen.in`.
=> [c#] Fix rebuilds when using BondCodegen.Options

examples/cpp/core/polymorphic_container/polymorphic_container.bond, examples/cpp/core/polymorphic_container/polymorphic_container.cpp
Switch polymorphic_container example from using `bond_meta::full_name` to using a kind enum to show current best practices.
=> Demonstrate kind enum in polymorphic_container example

cs/src/comm/epoxy-transport/EpoxyTransport.cs, cs/src/comm/interfaces/ILayer.cs, cs/src/comm/interfaces/ILayerStack.cs, cs/src/comm/layers/LayerStack.cs, cs/src/comm/layers/LayerStackUtils.cs, cs/src/comm/simpleinmem-transport/SimpleInMemTransport.cs, cs/test/comm/Epoxy/EpoxyTransportTests.cs, cs/test/comm/Layers/LayerStackTests.cs, cs/test/comm/SimpleInMem/SimpleInMemConnectionTest.cs
LayerStackProvider's constructor no longer requires a logger.
Defer initialization of the cached layer stack in the stateless case.
Pass in logger during send/receive operations instead.
=> [C# Comm] Remove logger from LayerStackProvider

cs/src/comm/epoxy-transport/EpoxyTransport.cs, cs/src/comm/simpleinmem-transport/SimpleInMemTransport.cs, cs/test/comm/Interfaces/ServiceIsolationTests.cs
Methods that never await anything except what they return can simply return
the Task that they were awaiting, eliminating some compiler-generated async
machinery.
=> [c# comm] Simplify redundant return await

CHANGELOG.md, cs/src/comm/epoxy-transport/EpoxyListener.cs, cs/src/comm/service/TaskExt.cs, cs/test/comm/Epoxy/EpoxyListenerTests.cs
- Don't block in the listener's accept loop waiting for one connection
to be established before accepting the next one.
=> [c# epoxy] Accept multiple connections in parallel

cs/nuget/App.config, cs/nuget/bond.comm.runtime.csharp.nuspec, cs/nuget/bond.compiler.csharp.nuspec, cs/nuget/bond.core.csharp.nuspec, cs/nuget/bond.csharp.test.csproj, cs/nuget/bond.runtime.csharp.nuspec, cs/nuget/packages.config, cs/src/json/JSON.csproj, cs/src/json/packages.config, cs/test/comm/comm.csproj, cs/test/comm/packages.config, cs/test/core/Core.csproj, cs/test/core/packages.config, examples/cs/core/simple_json/simple_json.csproj
I think this should resolve #171.
Adding support for NETStandard requires upgrading Newtonsoft.Json from 9.0.1, since that is the lowest version of that library that supports NETStandard.
Per https://docs.nuget.org/ndocs/schema/target-frameworks, the existing `Profile78` is equivalent to `netstandard1.0`, so that is what I used.
Per https://github.com/davidfowl/NetStandard/issues/5, the current way to support both PCL and NETStandard projects is to have a copy of the DLL in both lib folders in the NuGet package, so I added a `netstandard1.0` lib folder to the nuspec files that already had a `portable-net45+wp80+win8+wpa81+dnxcore50` lib folder.
All unit tests in `cs\cs.sln` and `cs\nuget\nuget.sln` passed, but I had to add an assembly binding redirect for `cs\nuget\nuget.sln` because it …
=> Add netstandard support to NuGet packages

cs/test/core/TypeAliasTests.cs, examples/cs/core/container_alias/program.cs
During the merge of commit 30b2c660a649fd6fc9d49e5df9d4bca0b33062cb,
SomeCustomList<T> lost its implementation of ICollection, a required
interface for a custom list-like container.
See also: https://github.com/Microsoft/bond/issues/254
=> [c#] Fix container alias tests and example

cs/nuget/.dir-locals.el, cs/nuget/bond.comm.csharp.nuspec, cs/nuget/bond.comm.epoxy.csharp.nuspec, cs/nuget/bond.comm.runtime.csharp.nuspec, cs/nuget/bond.compiler.csharp.nuspec, cs/nuget/bond.compiler.nuspec, cs/nuget/bond.core.csharp.nuspec, cs/nuget/bond.csharp.nuspec, cs/nuget/bond.runtime.csharp.nuspec
The intent is to make merging easier when we add/remote target
frameworks in the future.
* List target first so everything going to the same target can easily be
sorted together.
* Sort lines and split into logical sections.
=> [c#] Rearrange nuspec files by target

appveyor.yml
* Also make the pandoc build run in parallel
This gets the AppVeyor documentation build working again.
=> Constrain mtl to get pandoc to build again

cmake/Bond.cmake
- Add BUILD_ONLY as an argument to add_bond_test() CMake function
=> Add option to compile and not execute a specific test

.travis.yml
Travis's macOS VMs are just too slow to complete the C++ tests in any reasonable
amount of time.
=> Disable Travis CI for C++ on macOS.

CHANGELOG.md, README.md, doc/src/bond_comm.md, doc/src/bond_comm_roadmap.md, doc/src/bond_cpp.md, doc/src/bond_cs.md
Include initial C++ release and updates to C# implementation. Also,
update minimum version of Boost to 1.58.
=> Update Bond Comm docs

CHANGELOG.md, cs/src/core/expressions/DeserializerTransform.cs, cs/test/core/Core.csproj, cs/test/core/DeserializerControlsTests.cs, cs/test/expressions/DeserializeCB.expressions, cs/test/expressions/DeserializeJson.expressions, cs/test/expressions/DeserializeSP.expressions, cs/test/expressions/DeserializeXml.expressions
Provide controls that cap the amount of pre-allocation done for
containers and blobs.
This is intended as a failsafe against out-of-memory conditions when deserializing invalid data (e.g.: corrupted payloads), not for fine-grained control over per-request allocation.
=> [C#] Add preallocation controls in deserialization

cpp/inc/bond/comm/transport/detail/epoxy_data_structs.h
Addresses https://github.com/Microsoft/bond/issues/294
Includes a new example written by Christopher that reproduces the issue.
=> Address issue with multiple defines in C++ Comm

cpp/test/core/blob_tests.cpp, cpp/test/core/inheritance_test.cpp, cpp/test/core/list_tests.cpp, cpp/test/core/nullable.cpp, cpp/test/core/pass_through.cpp, cpp/test/core/serialization_test.cpp
This macro is less useful now that the tests have been exploded into
smaller executables.
=> [c++] Remove unused UNIT_TEST_SUBSET

CHANGELOG.md, compiler/Main.hs, compiler/bond.cabal, compiler/src/Language/Bond/Codegen/Cpp/Comm_cpp.hs, compiler/src/Language/Bond/Codegen/Templates.hs, compiler/tests/Tests/Codegen.hs
Renamed the file, the module, and the functions.
=> [gbc] Rename Types_Comm_cpp to Comm_cpp

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cs/Comm_cs.hs, compiler/tests/generated/generic_service_interfaces.cs, compiler/tests/generated/service_interfaces.cs
The interfaces were inadvertently internal before.
=> [c# epoxy] Make generated interfaces public

cmake/Config.cmake
Before this change, the build would look for pre-compiled gbc in a lot
of places on the system. It would often find gbc from a prior install of
Bond. However, this frequently causes the build to fail. Now, it only
looks for pre-compiled gbc in the directory specified by the environment
variable BOND_GBC_PATH. Alternatively, if the CMake variable
BOND_GBC_PATH is set, that will be used directly.
=> Require explicit opt-in to use pre-compiled gbc

doc/src/bond_cpp.md, doc/src/bond_cs.md
Type evolution rules added to C++ and C# manuals. Duplication will be addressed when https://github.com/Microsoft/bond/issues/115 is addressed.
=> Doc update to include type evolution rules

cs/src/comm/epoxy-transport/EpoxyNetworkStream.cs
If the function that produces the socket itself throws, we may not have a
socket to call Shutdown and Close on. This fixes a regression introducted by
2f9aeae.
=> [c# epoxy] Safely shutdown possibly null sockets

cmake/Config.cmake, cpp/CMakeLists.txt
The CMake cache variable `BOND_LIBRARIES_INSTALL_CPP` controls whether the
generated .cpp files are installed under src/. This can be used to keep the
code around for debugging purposes or to create a self-contained copy of
Bond that can be built with something other than CMake.
=> Add CMake option to install generated .cpp files

appveyor.yml
Instead of building pandoc from source, we now just use Chocolately to
install a precompiled version of pandoc. This speeds up documentation
builds and prevents random breakage due to Hackage package changes.
NB: The Chocolately Pandoc 1.19.2.1 package is currently broken. It
appears to have a pre-release Pandoc 2.0 executable that doesn't
understand all the command line flags that 1.x does (e.g., --smart).
Fixes https://github.com/Microsoft/bond/issues/341
=> Use precompiled pandoc for building documentation

compiler/bond.cabal
gbc-tests no longer builds with derive 2.6 or later. While we
investigate that problem, pin the dependency to < 2.6 to keep gbc-tests
building.
Mitigates https://github.com/Microsoft/bond/issues/342
=> [gbc] Temporarily pin derive dependency to < 2.6

CHANGELOG.md, cs/src/io/unsafe/InputStream.cs, cs/test/core/DeserializerControlsTests.cs, cs/test/core/StreamTests.cs
Prevent InputStream from preallocating large amounts of memory without reading from underlying stream in incremental chunks. Default is set to 128MB to prevent massive preallocation by corrupted data, similar to the DeserializerControls introduced in https://github.com/Microsoft/bond/pull/297
=> [C#] Cap incremental memory usage in InputStream

CHANGELOG.md, cmake/Compiler.cmake, cmake/Config.cmake, cpp/inc/bond/comm/address.h, cpp/inc/bond/comm/thread_pool.h, cpp/inc/bond/comm/transport/epoxy.h, cpp/inc/bond/comm/transport/thread_service.h, cpp/inc/bond/core/detail/metadata.h, cpp/inc/bond/core/detail/sdl.h, cpp/inc/bond/protocol/detail/rapidjson_helper.h, examples/cpp/comm/layer/CMakeLists.txt, examples/cpp/core/bf/err.h, examples/cpp/core/bf/input_file.h, examples/cpp/core/bf/main.cpp, examples/cpp/core/multiprecision/CMakeLists.txt
For projects that use Microsoft's SDL, these commits help minimize the amount of work needed to use Bond.
As a bonus, the changes are relatively contained, and don't materially affect Clang or GCC.
These commits should be rebased atop master, or a full merge should be done.
=> Improve Bond's compliance with Microsoft's SDL

cpp/inc/bond/stream/output_buffer.h
This make the init list order match the real order of initialization,
avoiding a warning from Clang/GCC.
=> [c++] Sort OutputBuffer init list and members uniformly

tools/boost-builder/build_boosts.zsh, tools/boost-builder/upload_boosts.zsh
Was advising a friend on shell scripting and realized I missed an important option here. -u causes the shell script to terminate if you try to expand an undefined variable.
=> boost-builder: Set -u in scripts.

CHANGELOG.md, cpp/inc/bond/core/parser.h
- remove pre-field instantiation of
DynamicParser<>::UnknownFieldOrTypeMismatch method to reduce generated
symbols
=> Optimize UnknownFieldOrTypeMismatch instances

cpp/inc/bond/comm/address.h
boost::asio 1.62 fails on mac/clang
**'OSMemoryBarrier' is deprecated**: first deprecated in macOS 10.12 - Use
std::atomic_thread_fence() from <atomic> instead
[-Werror,-Wdeprecated-declarations]
OSMemoryBarrier();
=> Work-around deprecated 'OSMemoryBarrier' on macOS

CHANGELOG.md
To build with Visual C++ 2017, we need a [fix from RapidJSON for the
_umul128 intrinsic][1]. This fix was first included in the v1.0.0
release of RapidJSON.
Fixes https://github.com/Microsoft/bond/issues/340
[1]: https://github.com/miloyip/rapidjson/commit/4b4f726dd810967498b81ef05f8ed62f04384968
=> [c++] Upgrade RapidJSON dependency to v1.0.0

cpp/inc/bond/core/apply.h, cpp/test/core/apply_tests.cpp
After introducing the two simpler overloads of `Apply` in #411 the case when passing a non-`const` reference to `bonded` selects an overload that takes non-`const T&` while corresponding `_apply.cpp` compiles it with `const` argument. This change fixes it by making sure that `Apply` accepting `T&` participates in overload resolution only for modifying transforms.
=> [c++] Fixing a regression in pre-compiled Apply functions

compiler/Main.hs
Fix regression introduced in https://github.com/Microsoft/bond/pull/418.
Shift Apply overload on CompactBinary protocol from OutputCounter to
CompactBinaryCounter.
=> [gbc] Change C++ Apply overload for output counter

cpp/test/core/apply_tests.cpp
Extend Apply test to prevent regression of Apply overload for CompactBinary v2 Pass0.
=> [C++] Cover CBv2 Pass0 counter in Apply test

cmake/Config.cmake
The original condition (`NOT (MSVC_VERSION LESS 1900)`) was triggering
for Visual C++ 2015 as well.
* Visual C++ 2015 has a `MSVC_VERSION` of 1900.
* Visual C++ 2017 has a `MSVC_VERSION` of 1910.
The original error was not caught, as it was causing the _command line
warning_ "Command line warning D9002 : ignoring unknown option
'/permissive-'" to be emitted. The CI builds don't fail on these sort of
warnings. (The cl.exe switch `/WX` does not turn this warning into a
non-zero exit code.)
=> [c++] Only use /permissive- on VC++ 2017 and later

compiler/bond.cabal
The Hackage package ansi-terminal as of version 0.6.3 is no longer
building with GHC 7.8.3, which causes out CI builds to fail.
Issue https://github.com/feuerbach/ansi-terminal/issues/22 has been
opened about this, but until it is resolved, we need to use an earlier
version.
=> [gbc] Pin gbc-tests to ansi-terminal < 0.6.3

cpp/inc/bond/ext/detail/barrier.h, cpp/inc/bond/ext/detail/countdown_event.h, cpp/inc/bond/ext/detail/event.h
For wait()-like functions we now take std::chrono::duration arguments by
const reference, just like std::condition_variable does.
=> [c++ grpc] Take durations by const reference

cpp/inc/bond/ext/detail/barrier.h, cpp/inc/bond/ext/detail/countdown_event.h, cpp/inc/bond/ext/detail/event.h, cpp/test/compat/comm/pingpong_server.cpp, cpp/test/compat/grpc/pingpong_server.cpp, cpp/test/grpc/io_manager.cpp, cpp/test/grpc/thread_pool.cpp, cpp/test/grpc/wait_callback.cpp, examples/cpp/grpc/pingpong/pingpong.cpp
The wait member function of barrier, countdown_event, and event that
takes a timeout has been renamed to wait_for to match
std::condition_variable.
=> [c++ grpc] Rename sync objects' wait to wait_for

doc/src/bond_cpp.md, doc/src/bond_cs.md
* Add an explicit section about default values
* Be explicit about what field types can have explicit vs. implicit vs.
nothing default values.
* Improve cross-references.
* Copy relevant sections for C++ manual to C# manual. (This is the best
we can do until we switch to something that let's us import section
into multiple pages.
Closes https://github.com/Microsoft/bond/issues/464
=> [doc] Refine nullable, nothing, and default values

cpp/inc/bond/stream/stream_interface.h
The unspecialized custom stream inferface functions that exist solely to
describe the interface have static asserts that are always false.
However, they are also non-void functions that have no return
statements. g++ 5.4.0 emits a warning about the lack of a return
statement. It apparently cannot see that the static assert is always
false. BOND_NORETURN is used to indicate that these methods don't
actually ever return anything.
=> [c++] Mark custom stream interface BOND_NORETURN

.travis.yml, README.md, cpp/inc/bond/ext/grpc/detail/client_call_data.h
ClientAsyncResponseReader had a breaking API change that we needed to
adjust to.
The gRPC zlib submodule is now conflicting with the system-wide zlib.
When using CMake inside of Travis, we prefer the system-wide zlib
package over the submodule.
There also appears to be a bug with ClientAsyncResponseReader's
placement new and placement delete operators, so we're consuming a
slightly patched version (see
https://github.com/chwarr/grpc/commit/8bd0fb92ec for the delta).
Upstream issue https://github.com/grpc/grpc/issues/11301 has been opened
about this problem.
This PR supersedes #467, which was closed with the underlying grpc++ branch was merged into master and deleted.
=> [c++ grpc] Upgrade to gRPC v1.3.4

compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs, compiler/tests/generated/generic_service_grpc.h, compiler/tests/generated/service_attributes_grpc.h, compiler/tests/generated/service_grpc.h, cpp/inc/bond/ext/grpc/client_callback.h, cpp/inc/bond/ext/grpc/detail/client_call_data.h, cpp/inc/bond/ext/grpc/unary_call.h, cpp/inc/bond/ext/grpc/wait_callback.h, cpp/test/compat/grpc/pingpong_client.cpp, cpp/test/grpc/io_manager.cpp, cpp/test/grpc/wait_callback.cpp, doc/src/bond_over_grpc.md, examples/cpp/grpc/grpc_dll/using_grpc_dll.cpp, examples/cpp/grpc/grpc_static_library/client/grpc_static_library_client.cpp, examples/cpp/grpc/helloworld/helloworld.cpp, examples/cpp/grpc/pingpong/pingpong.cpp
Here's a checkpoint of some work to improve the ClientContext lifetime management that @chadwalters  and I've been working on. This PR is here to get Travis and AppVeyor runs and as a place to collect comments. I expect it will be reworked heavily before being merged.
Current improvements:
* take ClientContext via shared pointer in the proxy methods so the context can be kept alive for the duration of the client call. Before, this was the client's responsibility, and failure to do so resulted in crashes.
* include the ClientContext in what's passed back to the callback so that the caller can "forget" about the context if they don't need it in the interim
* minimize copies by reading the response and status into a client_callback_args that we then move into the callback
Potential future …
=> ClientContext lifetime improvements (WIP)

CHANGELOG.md, cpp/inc/bond/comm/wire_protocol.h, cpp/inc/bond/core/detail/validate.h, cpp/inc/bond/protocol/detail/rapidjson_helper.h
v1.1 addresses warning from clang. Also, fix some issues in VC++ that the
upgrade exposed, specifically:
* Unreachable code warnings in several places
* Conflicts due to mix/max macros in windef.h
* Warning due to converting enum to uint16_t
Resolves https://github.com/Microsoft/bond/issues/485
=> [C++] Upgrade rapidjson to v1.1

cpp/inc/bond/core/reflection.h
Commit fd9a186676cf switched from boost::integral_constant to
std::integral_constant, but didn't make a clean break. With this change,
everything now uses std::integral_constant.
CC: @jdubrule
=> [c++] Remove last boost::integral_constant uses

java/compat/build.gradle, java/core/.idea/modules/bond.iml, java/core/build.gradle, java/gradle-plugin/.idea/misc.xml, java/gradle-plugin/.idea/modules/bond-gradle.iml, java/gradle-plugin/src/main/groovy/com/microsoft/bond/gradle/BondCodegen.groovy, java/gradle-plugin/src/main/groovy/com/microsoft/bond/gradle/BondPlugin.groovy, java/gradle-plugin/src/main/groovy/com/microsoft/bond/gradle/BondProdCodegen.groovy, java/gradle-plugin/src/main/groovy/com/microsoft/bond/gradle/BondTestCodegen.groovy
This also renames the bond codegen tasks to mirror their Java counterparts. The second commit cleans up some stray libraries that were automatically added, some of which come from the first.
A fresh build on core now looks like this:
```
[ted@pike 16:21]{3}\% gradle build
:compileBond
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processResources NO-SOURCE
:classes
:jar
:assemble
:compileTestBond
:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning …
```
=> gradle plugin: Support src/test/bond.

CHANGELOG.md, cs/src/core/Reflection.cs, cs/test/core/TypeAliasTests.cs, cs/test/core/Util.cs, cs/test/internal/ReflectionTests.cs
Reflection.IsBonded now correctly returns true for custom IBonded
implementations. In addition, corrected reversed logic in test utility
code that was likely related to the incorrect predicate.
=> [C#] Fix Reflection.IsBonded for custom IBonded implementations

.travis.yml, README.md, appveyor.yml, cmake/Config.cmake
Need to check that CI not only passes, but that each flavor includes or does not include Comm, as appropriate.
=> [C++] Don't build Comm by default.

CHANGELOG.md, appveyor.yml, cs/Compiler.vcxproj, cs/build/internal/Common.Internal.props, cs/build/internal/Common.Internal.targets, cs/build/internal/Portable.Internal.props, cs/dnc/src/json/project.json, cs/dnc/test/core.tests/project.json, cs/nuget/bond.csharp.test.csproj, cs/nuget/bond.runtime.csharp.nuspec, cs/nuget/packages.config, cs/src/json/JSON.csproj, cs/src/json/expressions/json/SimpleJsonParser.cs, cs/test/core/Core.csproj, cs/test/core/SerializationTests.cs, cs/test/core/Util.cs, examples/cs/core/simple_json/simple_json.csproj
Newtonsoft JSON.NET supports uint64 where BigInteger is supported. This pull request allows Bond's SimpleJsonProtocol to leverage that support.
=> [C#] Add support for uint64 in JSON when possible

CHANGELOG.md, cs/src/io/unsafe/InputStream.cs, cs/test/core/StreamTests.cs
InputStream would always try to call Stream.Seek when it needed to skip
over some bytes in the underlying stream, even if the stream didn't
support Seek.
Now, it checks whether the stream can seek. If not, it makes dummy Read
calls to advance the underlying stream.
Regression test added, and all the implementations of IInputStream that
ship with Bond are tested against these tests.
Existing InputStream tests folded into these IInputStreams tests, and
tested against both seekable and non-seekable streams.
Fixes https://github.com/Microsoft/bond/issues/498
=> [c#] Handle non-seekable streams in InputStream

cpp/test/comm/CMakeLists.txt, cpp/test/comm/basic.cpp, cpp/test/comm/core.cpp, cpp/test/comm/error.cpp, cpp/test/comm/forward.cpp, cpp/test/comm/generic_service.cpp, cpp/test/comm/generic_type.cpp, cpp/test/comm/idl.cpp, cpp/test/comm/jumbo.cpp, cpp/test/comm/layers.cpp, cpp/test/comm/protocol.cpp, cpp/test/comm/timeout.cpp, cpp/test/compat/comm/CMakeLists.txt, cpp/test/compat/comm/pingpong_client.cpp, cpp/test/compat/comm/pingpong_server.cpp, cpp/test/compat/grpc/CMakeLists.txt, cpp/test/compat/grpc/pingpong_client.cpp, cpp/test/compat/grpc/pingpong_server.cpp
In some CMakeLists.txt files, codegen was being run on the same .bond
files multiple times. Depending on build scheduling, this could result
in build failures (if the generation were to happen at the same time) or
spurious rebuilds (due to spurious rewrites of the generated files).
Now, .bond files that are shared across targets within the same
directory are generated once and compiled into a static library that is
then linked into all the consumers.
Since we're compiling the .bond files into a static library, we can take
advantage of the _apply.cpp precompilation as well.
=> [c++] Fix potential simultaneous codegen

README.md
Also, lay out the CMake commands following the template that `cmake
--help` documents: `cmake [options] <path-to-source>`
Partial fix for https://github.com/Microsoft/bond/issues/535
=> Skip gRPC for initial build on macOS in README

CHANGELOG.md, cpp/inc/bond/core/value.h, cpp/test/core/marshal.cpp
* Deserialize was used as the name for both a struct and a member
function. This causes some versions of G++ to emit errors, so rename
the helper struct. Fixes https://github.com/Microsoft/bond/issues/538
* The Protocols template argument could not be deduced in one place
where bond::SelectProtocolAndApply was called. It is now explicitly
specified.
=> [c++] Fix G++ 5.4 errors

CHANGELOG.md
=> Indicate that version 6.0.1 was not used.

cpp/inc/bond/protocol/simple_binary.h, cs/src/core/protocols/SimpleBinary.cs
This cherry-picks the fixes I made to `simple_binary.h` in `jvm` and applies them to `SimpleBinary.cs`, too.
=> c++/c# simple binary documentation fixes

examples/cs/core/serialization/program.cs, examples/cs/core/serialization/serialization.csproj
The previous code in the serialization example created a new
List<double> for the vector<double> field `items`, implying that the
field was not initialized to an empty List<double>.
Since the `items` field is initialized to an empty list, we now just
append to the existing list.
=> [c#] Append to list in serialization example

java/core/src/main/java/com/microsoft/bond/protocol/SimpleBinaryWriter.java
This addresses a request for a comment from #542 that I misunderstood at the time as targeting C#, not Java.
=> java core: Add doc for simple/omitted/=nothing interaction.

cs/cs.sln
When the schema_view example was merged into cs.sln in commit
1406febda4, a syntax error was introduced. This commit fixes that and
ensures that inheritance and schema_view have the correct
project-to-project dependencies as well.
=> [c#] Fix cs.sln inheritance project

compiler/src/Language/Bond/Codegen/Java/Class_java.hs, compiler/tests/generated/aliases_concatenated.java, compiler/tests/generated/attributes_concatenated.java, compiler/tests/generated/basic_types_concatenated.java, compiler/tests/generated/bond_meta_concatenated.java, compiler/tests/generated/complex_types_concatenated.java, compiler/tests/generated/defaults_concatenated.java, compiler/tests/generated/field_modifiers_concatenated.java, compiler/tests/generated/generics_concatenated.java, compiler/tests/generated/inheritance_concatenated.java, cs/Compiler.vcxproj, cs/Compiler.vcxproj.filters, java/core/src/main/java/com/microsoft/bond/StructBondType.java
This aligns with C++/C# implementations.
Also adds Java filter to compiler project in Visual Studio solution.
=> Fix Java StructDef full name to come from IDL

CHANGELOG.md, cs/src/core/protocols/CompactBinary.cs, cs/test/core/BondedTests.cs, cs/test/core/Util.cs
Serialization of bonded fields was interacting with the state in the CompactBinaryWriter because it triggered first-pass again. This fix prevents the first-pass writer from being returened in the middle of the
second pass.
=> [C#] Fix interaction with CBv2 and bonded fields 

java/core/src/main/java/org/bondlib/BondType.java, java/core/src/main/java/org/bondlib/Bonded.java, java/core/src/main/java/org/bondlib/EnumBondType.java, java/core/src/main/java/org/bondlib/Throw.java, java/core/src/test/bond/common.bond, java/core/src/test/bond/generic.bond, java/core/src/test/java/org/bondlib/GenericContainerTest.java, java/core/src/test/java/org/bondlib/TestHelper.java
In this change:
1. Fixed generic type parameters for set/map and bonded containers.
2. Added tests for the above, as well as testing generic containers in general.
3. Added a unit test helper to marshal/unmarshal and compare results. This is currently broken for Bonded due to lack of proper test for equality.
4. Identified and fixed a bug in EnumBondType triggered when a generic Enum type parameter was serialized
The fix for generic type parameters doesn't require any codegen changes. It involves overloading setOf/mapOf/bondedOf methods to take plain BondType (instead of PrimitiveBondType or StructBondType), which is what generated code will call from now on. The methods are protected since they are intended for generated code use only. The original public methods are unmodified and …
=> [Java] Fixed generic type parameters for set/map and bonded containers

examples/cs/core/date_time/program.cs
In order to avoid round-tripping problems due to changing local time
zones, the DateTime example now serializes and deserializes DateTime
instances as UTC.
This does mean, that if you have a Local DateTime that you round-trip,
you will get back a UTC DateTime instead. This is better expected
behavior than random time zone offset changes.
=> [c#] Always serialize DateTime as UTC

cmake/Config.cmake, cpp/inc/bond/core/detail/cmdargs.h, cpp/inc/bond/protocol/simple_json_reader_impl.h, cpp/test/compat/core/compat.cpp, cpp/test/core/metadata_tests.cpp
* `isspace` takes ints, not chars, so promote.
* Instead of dealing with a potentially non-null terminated string when
finding a field by ordinal in Simple JSON, attempt to parse the field
ID and then compare the numeric values.
* Indicate that the `die` function never returns so that the analyzer
can tell that we've checked for things like malloc returning null.
* The printf format string for unsigned ints is u, not d.
* Disable the code analysis warning C6326, "constant constant
comparison". A lot of our template functions trigger this when they do
things like: if (T == traits<U>::some_value) { ... } else { ... }
=> [c++] Fix some MSVC static analysis issues

java/compat/.idea/modules/compat.iml, java/core/.idea/modules/bond.iml, java/core/src/test/bond/bonded.bond, java/core/src/test/java/org/bondlib/protocol/CompactBinaryWriterTest.java
Locally reverted the bug fix from 8a608fbe and confirmed that the test fails with an `InvalidBondDataException`.
Additionally, accept IDEA's insistence on `out/` in a separate commit.
=> java core: Add regression test for CBv2 double bonded bug.

.travis.yml, cpp/test/compat/core/CMakeLists.txt, cpp/test/compat/core/compat.cmake, examples/java/core/protocol_versions/src/main/java/org/bondlib/ProtocolVersions.java
With these changes, Java gets built and tested, and all examples are run. One had a placeholder `assert false` that we should tackle immediately.
Everything works except for three cases in compat related to schemas and JSON. We need to get this green to get the benefit of CI, so I've disabled them in two places in the third commit. (One to avoid creating Java compat tests for `json` and `schema`, and another to do nothing with Java when the `gbc schema` test case comes through.)
=> travis: CI all Java components and run compat tests.

java/core/src/main/java/org/bondlib/StructBondType.java
This function's return value was read nowhere, and this should pass CI with no other changes.
=> java core: Make verifyDeserialized void.

CHANGELOG.md, cpp/inc/bond/protocol/simple_json_reader.h, cpp/test/core/json_tests.cpp
Use RapidJSON's iterative parser to handle deeply nested JSON data
without causing a stack overflow.
Added a unit test with a deeply nested JSON array to test this.
=> [c++] Use RapidJSON's iterative parser

compiler/bond.cabal
For Windows builds, pass linker flags to enable NX and as much of ASLR
as we can.
* We cannot move the base address above 4GiB, as the GHC runtime
libraries are not compiled to support this.
* The linker used by GHC doesn't support keeping reloc information
when emitting PE32+ executables. This will end up limiting the
effectiveness of ASLR, but we're doing what we can.
=> [gbc] Enable NX and limited ASLR for Windows builds

cpp/test/core/required_fields_tests.cpp
In the required_fields_tests, some unavoidable compiler warnings are
emitted. These are now suppressed at the file level.
* Since we're explicitly testing some exceptional code paths, some
expansions of StaticParser are expected to produce unreachable code.
* Some of the type names for the boost::mpl::list of schema fields in
these tests are too long for MSVC to handle without truncation.
=> [c++] Suppress unavoidable warnings

cpp/test/CMakeLists.txt, cpp/test/compat/core/serialization.cpp, cpp/test/core/unit_test_util.h
Instead of suppressing warning C4310 on the command line, we now
suppress it just where we need the truncation behavior.
=> [c++] Suppress MSVC warning 4310 locally

cpp/test/core/metadata_tests.cpp, cpp/test/core/unit_test_framework.h
When using MSVC, even with _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES and
_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT enabled, sometimes the
non-sprint_s overload is chosen when a stack buffer is used (the
array-to-pointer decay and the array-of-size-N template are competing
with each other, and the char* overload wins instead of the template).
To avoid, switch to using boost::format to format string in tests.
=> [c++] Use boost::format instead of sprintf in tests

java/core/src/main/java/org/bondlib/BlobBondType.java, java/core/src/main/java/org/bondlib/BondedBondType.java, java/core/src/main/java/org/bondlib/BoolBondType.java, java/core/src/main/java/org/bondlib/DoubleBondType.java, java/core/src/main/java/org/bondlib/EnumBondType.java, java/core/src/main/java/org/bondlib/FloatBondType.java, java/core/src/main/java/org/bondlib/Int16BondType.java, java/core/src/main/java/org/bondlib/Int32BondType.java, java/core/src/main/java/org/bondlib/Int64BondType.java, java/core/src/main/java/org/bondlib/Int8BondType.java, java/core/src/main/java/org/bondlib/ListBondType.java, java/core/src/main/java/org/bondlib/MapBondType.java, java/core/src/main/java/org/bondlib/NullableBondType.java, java/core/src/main/java/org/bondlib/SetBondType.java, java/core/src/main/java/org/bondlib/StringBondType.java, java/core/src/main/java/org/bondlib/StructBondType.java, java/core/src/main/java/org/bondlib/UInt16BondType.java, java/core/src/main/java/org/bondlib/UInt32BondType.java, java/core/src/main/java/org/bondlib/UInt64BondType.java, java/core/src/main/java/org/bondlib/UInt8BondType.java, java/core/src/main/java/org/bondlib/VectorBondType.java, java/core/src/main/java/org/bondlib/WStringBondType.java, java/core/src/main/java/org/bondlib/protocol/CompactBinaryWriter.java, java/core/src/main/java/org/bondlib/protocol/FastBinaryWriter.java, java/core/src/main/java/org/bondlib/protocol/ProtocolWriter.java, java/core/src/main/java/org/bondlib/protocol/SchemaHelper.java, java/core/src/main/java/org/bondlib/protocol/SimpleBinaryWriter.java
Changes:
1. Removed FieldMetadata and StructMetadata interfaces and replaced them with the Metadata Bond struct in protocol writers and BondType hierarchy.
2. Added SchemaHelpers class to abstract SchemaDef's intricacies, specifically default field values within a Variant struct.
3. Simplified SimpleBinaryProtocol's logic for getting field default values from schema.
4. Added SchemaDef property to StructBondType with caching (unable to do it at initialization time since that causes a circularity when initializing SchemaDef's own BondType). 
5. Fixed 2 bugs that are currently in other PR's: FieldDef was not added to field collection and initializing Variant with nothing led to null dereference.
=> [Java] Replaced field/struct metadata interfaces with SchemaDef's metadata

cpp/inc/bond/core/detail/string_stream.h
When using MSVC, even with _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES and
_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT enabled, sometimes the
non-sprint_s overload is chosen when a stack buffer is used (the
array-to-pointer decay and the array-of-size-N template are competing
with each other, and the char* overload wins instead of the template).
To avoid, switch to using std::to_string to format things in the
string_stream that is used to compute exception messages.
=> [c++] Switch to std::to_string in string_stream

CHANGELOG.md, cpp/inc/bond/core/detail/cmdargs.h, cpp/inc/bond/ext/grpc/bond_utils.h
Sometimes min/max are function-style macros, which interferes with use
of things like std::numeric_limits::max() and std::min(). An extra set
of parenthesis guards against this.
=> [c++] Guard against min/max being function macros

CHANGELOG.md, cpp/inc/bond/ext/grpc/detail/client_call_data.h
After executing the client callback upon receiving a response, clear the
stored callback to prevent a shared_ptr cycle.
Previously, when the callback function was not cleared, if the callback
happened to store the unary_call_result that it was invoked with (like
wait_callback does), there would be a shared_ptr cycle: the callback
would have a shared_ptr to the unary_call_result, which was keeping its
parent client_unary_call_data alive. This client_unary_call_data had a
copy of the callback function, which had a shared_ptr to the
unary_call_result.
This change resets the callback to empty after is has been executed,
breaking the cycle.
=> [c++ grpc] Drop client callback after executing

test/compat/grpc/pingpong.bond
PingLayerData was used in the old Bond Comm compat test, but is not
needed for the gRPC compat test.
=> [grpc] Remove PingLayerData from gRPC compat test

CHANGELOG.md, cs/nuget/bond.core.csharp.nuspec, cs/src/core/Bond.csproj, cs/src/core/protocols/SimpleXmlReader.cs, cs/test/core/Core.csproj, cs/test/core/DeserializerControlsTests.cs, cs/test/core/XmlParsingTests.cs, examples/cs/core/simple_xml/program.cs
By setting XmlReaderSettings.XmlResolver to null, we can avoid having
XmlReader resolve external XML entities. Attempting to resolve these
external entities can potentially access the network, which is not
something we want to do during deserialization.
This API only exists when targeting the full .NET 4.5 framework, hence
the need for a net45-nonportable version of Bond.dll.
=> [c#] Use null XmlResolver when possible

CHANGELOG.md, cs/src/core/expressions/DeserializerTransform.cs, cs/src/core/expressions/IParser.cs, cs/src/core/expressions/ObjectParser.cs, cs/src/core/expressions/SerializerTransform.cs, cs/src/core/expressions/TaggedParser.cs, cs/src/core/expressions/UntaggedParser.cs, cs/src/core/expressions/xml/SimpleXmlParser.cs, cs/src/json/expressions/json/SimpleJsonParser.cs, cs/test/core/ConvertTests.cs, cs/test/core/Core.csproj, cs/test/expressions/DeserializeCB.expressions, cs/test/expressions/DeserializeJson.expressions, cs/test/expressions/DeserializeSP.expressions, cs/test/expressions/DeserializeXml.expressions, cs/test/expressions/Expressions.csproj, cs/test/expressions/Program.cs, cs/test/expressions/SerializeCB.expressions, cs/test/expressions/SerializeSP.expressions, cs/test/expressions/SerializeXml.expressions, cs/test/expressions/TranscodeCBSP.expressions, cs/test/expressions/TranscodeSPCB.expressions, cs/test/expressions/schemas.bond
There were extra conversions of aliased blobs during serialization. Now each blob is only converted once.
Also, updated the expressions tests to include aliased blobs.
=> Remove extra blob conversions during serialization

CHANGELOG.md, cpp/inc/bond/core/detail/mpl.h, cpp/inc/bond/core/traits.h, cpp/inc/bond/stream/stream_interface.h, cpp/test/core/numeric_conversions.h
Macro parameters with commas in them, like "std::map<int, std::string>"
need to be surrounded with parenthesis so they are treated as one
parameter instead of as two parameters to the macro.
Standardize where the ! is in parthensized parameters.
=> [c++] Surround macro parameters with parenthesis

cs/cs.sln
* The project type GUID was still for a C++ project. It has been
switched to a C# project.
* This caused a platform change from Win32 to Any CPU
* The cloning example was missing a solution-level dependency on
Bond.IO.dll. One has been added.
=> [c#] Fix cs.sln load in Visual Studio 2015/2017

compiler/src/Language/Bond/Codegen/Java/Class_java.hs, compiler/tests/generated/aliases_concatenated.java, compiler/tests/generated/attributes_concatenated.java, compiler/tests/generated/basic_types_concatenated.java, compiler/tests/generated/basic_types_nsmapped_concatenated.java, compiler/tests/generated/bond_meta_concatenated.java, compiler/tests/generated/complex_types_concatenated.java, compiler/tests/generated/defaults_concatenated.java, compiler/tests/generated/field_modifiers_concatenated.java, compiler/tests/generated/generics_concatenated.java, compiler/tests/generated/inheritance_concatenated.java, java/core/src/main/java/org/bondlib/BondSerializable.java, java/core/src/test/bond/generic.bond, java/core/src/test/java/org/bondlib/JavaNativeSerializationTests.java
The actual serialization is CBv1 marshalling. With this commit, attempting to put a generic Bond-generated type through an API expecting a Serializable will throw.
I checked whether we could get rid of `serialVersionUID` - looks like the header and the fqcn/sVUID matching logic are the same between `Serializable` and `Externalizable`. See more [here](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4094702).
=> java core: Implement j.io.Serializable for concrete types.

CHANGELOG.md
A minor version bump is needed due to the new operator= added in commit
0d911ca9.
[skip ci]
=> [c++] Update changelog: minor bump needed

appveyor.yml
This list is not exhaustive (e.g., CONTRIBUTING.md is not included). To
keep it maintainable, it only contains high-churn files that don't
affect the build.
* CHANGELOG.md doesn't affect the build but get changes almost daily.
* Travis CI-specific files don't affect the Windows builds.
=> [appveyor] Skip AppVeyor builds for boring files

CHANGELOG.md, cpp/inc/bond/ext/grpc/bond_utils.h
The caller of grpc_byte_buffer_reader_next is responsible for calling
grpc_slice_unref on the slice. However, SerializationTraits::Deserialize
was only calling grpc_slice_unref on the last slice. Now, it is called
on each slice.
Also fixes a potential bug that would call grpc_slice_unref on an
uninitialized slice.
=> [c++ grpc] Fix multi-slice deser. memory leak

java/gradle-plugin/README.md
Previously merged as #683, but appears to have fallen between the cracks during the jvm merge into master. Please squash.
=> java gradle: Update README to use a pom.

.gitmodules, CHANGELOG.md, cpp/inc/bond/ext/grpc/detail/client_call_data.h, cpp/inc/bond/ext/grpc/detail/unary_call_impl.h, cpp/test/compat/grpc/CMakeLists.txt, cpp/test/grpc/CMakeLists.txt, examples/cpp/grpc/async-server/CMakeLists.txt, examples/cpp/grpc/grpc_dll/CMakeLists.txt, examples/cpp/grpc/grpc_static_library/CMakeLists.txt, examples/cpp/grpc/helloworld/CMakeLists.txt, examples/cpp/grpc/pingpong/CMakeLists.txt, examples/cpp/grpc/scalar/CMakeLists.txt
Pick up a bug fix in commit gRPC 7269667f (initially implemented for C++
in gRPC commit be9b8142) for channel disconnections we've been
observing.
=> [c++ grpc] Upgrade to gRPC v1.7.1

examples/cpp/core/polymorphic_container_visitor/polymorphic_container_visitor.bond, examples/cpp/core/polymorphic_container_visitor/polymorphic_container_visitor.cpp, examples/cpp/core/polymorphic_container_visitor/polymorphic_visitor.h
Switch the polymorphic_container_visitor example to use a Kind enum
instead of the deprecated bond_meta::full_name.
TODO:
=> [c++] Use Kind enum in polymorph. cont. visitor

README.md
When merging please delete the "[skip ci]" from the commit message. We want to trigger a doc build with AppVeyor.
=> [doc] Improve Linux build instructions

compiler/src/Language/Bond/Codegen/Cpp/Types_cpp.hs, compiler/src/Language/Bond/Syntax/SchemaDef.hs, compiler/src/Language/Bond/Syntax/Util.hs, compiler/tests/generated/aliases_types.cpp, compiler/tests/generated/alloc_ctors/aliases_types.cpp, compiler/tests/generated/alloc_ctors/attributes_types.cpp, compiler/tests/generated/alloc_ctors/defaults_types.cpp, compiler/tests/generated/alloc_ctors/with_enum_header_types.cpp, compiler/tests/generated/allocator/aliases_types.cpp, compiler/tests/generated/allocator/attributes_types.cpp, compiler/tests/generated/allocator/defaults_types.cpp, compiler/tests/generated/allocator/with_enum_header_types.cpp, compiler/tests/generated/attributes_types.cpp, compiler/tests/generated/defaults_types.cpp, compiler/tests/generated/scoped_allocator/aliases_types.cpp, compiler/tests/generated/scoped_allocator/attributes_types.cpp, compiler/tests/generated/scoped_allocator/defaults_types.cpp, compiler/tests/generated/scoped_allocator/with_enum_header_types.cpp, compiler/tests/generated/type_aliases/aliases_types.cpp, compiler/tests/generated/type_aliases/attributes_types.cpp, compiler/tests/generated/type_aliases/defaults_types.cpp, compiler/tests/generated/type_aliases/with_enum_header_types.cpp, compiler/tests/generated/with_enum_header_types.cpp
Currently, `boost::assign::map_list_of` is used to initialize C++ enum maps. This change makes use of [list initialization](http://en.cppreference.com/w/cpp/language/list_initialization) available in `c++11` which is more appropriate and avoids extra dependency on template-heavy boost headers.
=> [gbc c++] Use init. list for populating enum maps

compiler/src/Language/Bond/Codegen/Cpp/Reflection_h.hs, examples/cpp/core/dll/dll.bond, examples/cpp/core/dll/using_dll.cpp
Currently, the `--export-attribute` is used to mark all static `bond::Metadata` fields in compile-time `Schema` object, including the cases when the type is a template, which is not correct. This fixes the `gbc` to skip the attribute in such cases.
=> [gbc c++] Fix to not apply attrib. to generics

compiler/src/Language/Bond/Codegen/Cpp/Util.hs, compiler/tests/generated/alloc_ctors/attributes_reflection.h, compiler/tests/generated/alloc_ctors/attributes_types.cpp, compiler/tests/generated/allocator/attributes_reflection.h, compiler/tests/generated/allocator/attributes_types.cpp, compiler/tests/generated/attributes_reflection.h, compiler/tests/generated/attributes_types.cpp, compiler/tests/generated/scoped_allocator/attributes_reflection.h, compiler/tests/generated/scoped_allocator/attributes_types.cpp, compiler/tests/generated/service_attributes_comm.cpp, compiler/tests/generated/service_attributes_grpc.cpp, compiler/tests/generated/type_aliases/attributes_reflection.h, compiler/tests/generated/type_aliases/attributes_types.cpp, cpp/inc/bond/core/reflection.h
Currently, `boost::assign::map_list_of` is used to initialize C++ metadata attribute maps. This change makes use of [list initialization](http://en.cppreference.com/w/cpp/language/list_initialization) available in `c++11` which is more appropriate and excludes the dependency on boost header.
=> [gbc c++] Use init. list for populating attr. map

cmake/FindJavaBuildTools.cmake, cmake/Java.cmake, examples/java/core/blob/build.gradle, examples/java/core/enumerations/build.gradle, examples/java/core/generic_tree/build.gradle, examples/java/core/generics/build.gradle, examples/java/core/imports/build.gradle, examples/java/core/inheritance/build.gradle, examples/java/core/nothing_default/build.gradle, examples/java/core/polymorphic_container/build.gradle, examples/java/core/protocol_versions/build.gradle, examples/java/core/record_streaming/build.gradle, examples/java/core/runtime_schema/build.gradle, examples/java/core/schema_view/build.gradle, examples/java/core/serialization/build.gradle, examples/java/core/untagged_protocols/build.gradle, java/compat/CMakeLists.txt, java/compat/build.gradle, java/core/CMakeLists.txt, java/core/build.gradle, java/gradle-plugin/CMakeLists.txt, java/gradle-plugin/README.md, java/gradle-plugin/build.gradle, java/json/build.gradle, tools/ci-scripts/linux/image-builder/Dockerfile
This commit removes the need for the mvn binary and converts all
Java dependencies within the repo to true dependencies, rather than file
references. It also generates automatic versions for the core and
gradle-plugin projects from git tags.
=> java: Allow maven publication and clean up.

cpp/test/core/CMakeLists.txt
Fixes https://github.com/Microsoft/bond/issues/723
=> [c++] Skip core_test_common in default build

cpp/inc/bond/core/transforms.h
The change adds overloads of `Serializer::Field` function that avoids generating calls to `detail::omit_field` in the cases where the result is known at compilation. This makes the compilation a bit faster (it depends on actual types being used, but the expected estimate would be 3-5%) and also likely to generate faster, smaller and more efficient runtime code when compiler fails to optimize away the above calls.
=> [c++] Faster Serializer::Field

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs, compiler/tests/generated/generic_service_grpc.h, compiler/tests/generated/service_attributes_grpc.h, compiler/tests/generated/service_grpc.h
When a service contains events or parameterless methods, the generated
code uses bond::Void as the request/result type. To serialize
bond::Void, bond_reflection.h needs to be included.
The generated service code now includes bond_reflection.h if any service
contains an event or a parameterless method.
Fixes https://github.com/Microsoft/bond/issues/735
=> [c++ grpc] Fix includes when bond::Void is used

CHANGELOG.md, cpp/inc/bond/core/detail/inheritance.h, cpp/inc/bond/core/parser.h, cpp/inc/bond/core/transforms.h, cpp/test/core/inheritance_test.cpp, cpp/test/core/unit_test.bond, python/test/core/unit_test.py
With this change deserialization will now fail by throwing `bond::CoreException` when `BT_STOP` is encountered while deserializing a base struct.
Fixes https://github.com/Microsoft/bond/issues/742
=> [c++] Fix base to derived deserialization

cpp/inc/bond/core/parser.h
Simplifies the `DynamicParser<Input>::UnknownFieldOrTypeMismatch` function for basic types by excluding some run-time code paths.
=> [c++] Improve UnknownFieldOrTypeMismatch

cpp/inc/bond/core/bonded_void.h, cpp/inc/bond/core/detail/protocol_visitors.h
Simplifies the `bonded<void, Reader>::_Apply` function when used with protocols that specify `uses_marshaled_bonded<Reader>` to be `false_type` (currently all except `Simple`) by excluding some run-time code paths.
=> [c++] Improve bonded<void, Reader>::_Apply

cpp/inc/bond/core/detail/omit_default.h, cpp/inc/bond/core/parser.h
Simplifies the `StaticParser<Input>::ReadFields` function when used with protocols that do not implement field omitting by excluding some run-time code paths.
=> [c++] Improve StaticParser<Input>::ReadFields

cpp/inc/bond/ext/grpc/detail/client_call_data.h, cpp/inc/bond/ext/grpc/detail/unary_call_impl.h
The `bond::ext::gRPC::io_manager` expects pointers to `bond::ext::gRPC::io_manager_tag` base when it receives `void*` tags. However, we are are directly passing a pointer to derived type instead of explicitly casting to base (which does not cause issues due to current layout of those objects).
=> [c++ grpc] Fix incorrect casts to void*

CHANGELOG.md, cpp/inc/bond/ext/grpc/io_manager.h
Fixes a race condition when `bond::ext::gRPC::io_manager::shutdown` and `bond::ext::gRPC::io_manager::wait` are called concurrently. The functions are not mutually exclusive and the latter destroys the `grpc::CompletionQueue` which is not necessary.
Fixes #744
=> [c++ grpc] Fix race in io_manager

CHANGELOG.md, cpp/inc/bond/ext/grpc/detail/unary_call_impl.h
Fixes a race condition in `bond::ext::gRPC::detail::unary_call_impl` when one thread tries to send an error by calling `FinishWithError` when reference count becomes 1 during destruction, and the other thread that tries to perform `delete this` since the reference count becomes 0 due to a prior call to `Finish` by the user.
=> [c++ grpc] Fix race in unary_call destruction

tools/ci-scripts/linux/image-builder/build_boosts.zsh
This is the first step in enabling Boost 1.66 CI build on Travis. After
an image is produced that contains Boost 1.66, we still need to consume
that image in .travis.yml and add 1.66 to the configuration matrix.
I've locally tested that Bond builds and the basic tests pass with Boost
1.66 using Clang.
=> [travis] Add Boost 1.66 to CI image builder script

cpp/inc/bond/protocol/compact_binary.h, cpp/inc/bond/protocol/fast_binary.h
The change makes more compile-time dispatch on `BondDataType` in protocols' `Skip` functionality instead of relying on compiler's optimization.
=> [c++] Improve compact/fast binary protocols' Skip

cpp/test/grpc/io_manager.cpp
grpc::Alarm takes a void*, but io_manager expects io_manager_tag*. Thus,
we should have be casting alarm_completion_tag* to io_manager_tag*.
=> [c++] Add missing static_casts in io_manager tests

.gitmodules
When using CMake to build, the zlib submodule inside of the grpc
submodule ends up with a generated file that makes Git consider the
submodule dirty. This state can be ignored for day-to-day development.
=> Ignore dirty grpc submodule

doc/src/compiler.md
* Remove duplicate "Service" section.
* Remove incorrect "Service method" that talked about passing messages
and services, which was never implemented in gbc.
=> [gbc] Clean up service AST documentation

compiler/stack_build.cmake
Per [cmake docs](https://cmake.org/cmake/help/v3.0/command/execute_process.html), if you set both `OUTPUT_VARIABLE` and `ERROR_VARIABLE` to the same var, it will contain both streams' lines, merged in the order they were printed.
=> stack cmake: Print out errors from failed stack steps.

tools/ci-scripts/linux/image-builder/Dockerfile
Use the "headless" JDK in the Travis CI image to avoid installing a
bunch of X11 (and related) packages that we don't need. This also
reduces the size of the image.
After getting this commit into master, the next step is to wait for a
new image to be built and then consume that image in .travis.yml.
Here's a Travis CI run with the Java leg passing using the headless JDK: https://travis-ci.org/Microsoft/bond/jobs/339709515
I'll update this PR with the size reduction when I build a full image with the headless JDK. For testing, I ripped out a bunch of C# and C++ parts, so I don't have comparable numbers yet.
[skip ci]
=> [travis java] Switch to openjdk-8-jdk-headless

README.md
We already do this for our CI image.
=> Recommend curlbashing Stack instead of package management.

cpp/inc/bond/core/transforms.h
The `UnknownField` is expected to accept a non-trivial type `bond::value`, so `...` should not be used.
=> [c++] Fix To::UnknownField to do not use ellipses

.travis.yml, tools/ci-scripts/linux/image-cleanup/.gitignore, tools/ci-scripts/linux/image-cleanup/.pylintrc, tools/ci-scripts/linux/image-cleanup/collect_images.py, tools/ci-scripts/linux/image-cleanup/collector/acr.py, tools/ci-scripts/linux/image-cleanup/collector/config.py, tools/ci-scripts/linux/image-cleanup/collector/garbage_manifests.py, tools/ci-scripts/linux/image-cleanup/collector/live_images.py, tools/ci-scripts/linux/image-cleanup/mypy.ini
Every change (well, most every) to the master branch produces a new
Docker image (for our Linux CI builds). However, we don't use each new
image. Instead, occasionally someone updates .travis.yml to point to a
new image. Thus, there's a build up of Docker images in the repository
that aren't being used.
These images are garbage: garbage in the sense that they're not
reachable from any of the .travis.yml roots.
This commit adds a script that can be used to find and remove these
garbage images.
Given a set of filters to find root commits (e.g., we can specify all
tags and all commits in the past two weeks), the script finds all the
referenced Docker images in the various revisions to .travis.yml. It
then compares the referenced images to those present in the repository,
skips images that …
=> [travis] Add garbage CI image clean up script

tools/ci-scripts/linux/image-builder/README.md, tools/ci-scripts/linux/image-cleanup/collector/acr.py
Now that the garbage collector script has been running successfully for
a few days and we've validated its results, we can change it to actually
delete images instead of just printing which ones it would delete.
Fixes https://github.com/Microsoft/bond/issues/800
=> [travis] Delete garbage Docker images for real

cpp/inc/bond/core/value.h
The following code does not compile on clang. The issue does not occur on MSVC and GCC due to active bugs.
```cpp
bond::InputBuffer input;
bond::CompactBinaryReader<bond::InputBuffer> reader{ input };
bond::value<uint32_t, decltype(reader)&> value{ reader };
uint8_t var;
value.Deserialize(var); // Deserialize into a non-matching type
```
The issue is that all the SFINAE-enabled overloads of `Deserialize` inside of the base `bond::value_common` and derived `bond::value` have the same signature (e.g. all use the return type for SFINAE check and the rest of the signature is identical), so the one in the base class cannot be found because it will be shadowed by the ones in derived class. The fix is to change the signature of the base `Deserialize` by using a default parameter for a SFINAE …
=> [c++] Fix value::Deserialize of non-matching types

.gitmodules
The grpc submodule itself now marks it's zlib submodule as "ignore =
dirty", so we no longer have to do that for grpc just to ignore zlib.
=> [c++ grpc] Don't ignore dirty grpc submodule

compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs, compiler/tests/generated/generic_service_grpc.h, compiler/tests/generated/service_attributes_grpc.h, compiler/tests/generated/service_grpc.h, cpp/inc/bond/ext/grpc/bond_utils.h, cpp/inc/bond/ext/grpc/client_callback.h, cpp/inc/bond/ext/grpc/detail/client_call_data.h, cpp/inc/bond/ext/grpc/detail/service.h, cpp/inc/bond/ext/grpc/detail/service_call_data.h, cpp/inc/bond/ext/grpc/detail/unary_call_impl.h, cpp/inc/bond/ext/grpc/io_manager.h, cpp/inc/bond/ext/grpc/server.h, cpp/inc/bond/ext/grpc/server_builder.h, cpp/inc/bond/ext/grpc/wait_callback.h, cpp/test/grpc/io_manager.cpp
The gRPC++ headers were moved from grpc++ to grpcpp as part of [gRPC
proposal L22, "gRPC C++ Public Header Directory Change"][1].
Fixes https://github.com/Microsoft/bond/issues/813
[1]: https://github.com/grpc/proposal/blob/master/L22-change-grpc%2B%2B-dir-name.md
=> [c++ grpc] Switch to grpcpp include path

cs/build/nuget/Common.targets
In a [recent commit][1] the contract for the RemoveDuplicates task was
strengthened. So, we're no longer relying on implementation beahvior but
contractual behavior.
[1]: https://github.com/MicrosoftDocs/visualstudio-docs/commit/a050dde415255c4875d2d706295f42340ac06589
=> [cs] Clean up comment re: implementation details

CHANGELOG.md, cs/dnc/src/attributes/project.json, cs/dnc/src/core/project.json, cs/dnc/src/grpc/project.json, cs/dnc/src/io/project.json, cs/dnc/src/json/project.json, cs/dnc/src/reflection/project.json, cs/dnc/test/codegen/no-warnings.tests/project.json, cs/dnc/test/compat/compat.core.tests/project.json, cs/dnc/test/core.tests/project.json, cs/dnc/test/expressions.tests/project.json, cs/dnc/test/grpc.tests/project.json, cs/dnc/test/internal.tests/project.json
Previously, we were just [public signing][1] the .NET Core assemblies.
We intended to fully strong-name sign them, so this commit removes the
"publicSign": true entry from the project files.
[1]: https://github.com/dotnet/roslyn/commit/ca61bad288c1d2e216281680fe92ff55d7122e7f
=> [c#] Fully strong-name sign .NET Core assemblies

compiler/CMakeLists.txt, compiler/stack_build.cmake, cs/Compiler.csproj
We were always building gbc with GHC optimizations turned on. We can get
faster build times for things like CI if we don't build with optimizations.
To do that, we now pass different stack & gbc options for the various
CMake build types. The MSBuild Compiler.csproj project translates
MSBuild configurations into CMake configurations.
=> [gbc] Add debug/release Haskell configurations

compiler/tests/TestMain.hs, compiler/tests/Tests/Codegen.hs
In commit 3221200462, the gRPC golden tests for gbc were accidentally
removed, as they were being done in a function called
`verifyCsCommCodegen`. This commit restores them.
=> [c#] Restore gRPC golden tests for gbc

.travis.yml
This image is a little bit smaller, so should download marginally
faster. It will also help assure we don't take dependencies of libraries
that need an X server.
=> [travis] Consume image built with headless JDK

tools/ci-scripts/linux/build.zsh, tools/ci-scripts/linux/build_cpp-common.zsh, tools/ci-scripts/linux/build_cpp-core.zsh, tools/ci-scripts/linux/build_cpp-grpc.zsh
Splits the C++ build into its own set of scripts, like the other
flavors. This is in preperation for adding another C++ flavor: one that
builds with the gRPC master code instead of the current submodule
version.
=> [c++ travis] Split C++ build into its own scripts

.travis.yml, tools/ci-scripts/linux/build_java.zsh
Without this, Java will automatically configure a version string equal
to the checked-out hash prefix, which has a 6/16 chance of starting with
a letter instead of a number. Gradle doesn't seem to resolve
dependencies properly when this happens.
=> travis: Pull down git tags before starting the build.

.travis.yml, tools/ci-scripts/linux/build_cpp-grpc-master.zsh
This build flavor builds Bond with the latest gRPC master branch so we
can detect potential breaks faster than when we upgrade our submodule.
This build flavor isn't needed on every commit or pull request, so it's
only enabled for Travis's cron builds.
=> Build gRPC++ using latest gRPC master

cpp/inc/bond/ext/grpc/bond_utils.h
The use of `grpc_byte_buffer` in `SerializationTraits` is deprecated.
The update of `Deserialize` is currently blocked on https://github.com/grpc/grpc/issues/14880.
=> [c++ grpc] Use grpc::ByteBuffer in Serialize

.travis.yml, CHANGELOG.md, README.md, cmake/Config.cmake, tools/ci-scripts/linux/image-builder/build_boosts.zsh
Drops support for versions of Boost older than two years. Boost 1.61+ or
newer is now required. (Bond will likely continue to work with older
versions of Boost, but we'll no longer actively test against them.)
Using cron jobs, add coverage for all supported versions of Boost with
both Clang and G++.
This is the Travis-side fix for:
* https://github.com/Microsoft/bond/issues/666
* https://github.com/Microsoft/bond/issues/771
=> [travis] Test Boost 1.61+ with clang & g++

.travis.yml
This image was built from commit 3dc9704e. This image is 0.32 GiB
smaller than the previous one.
=> [travis] Consume image with only Boost 1.61+

CHANGELOG.md
This change has not yet been made, as it breaks the current AppVeyor
build.
Issue https://github.com/Microsoft/bond/issues/845 has been opened to
remind us to bump the minimum version later.
[skip ci]
=> [c++] Remove Boost min version from CHANGELOG

tools/ci-scripts/linux/image-builder/build_boosts.zsh
Using this image to test with Boost 1.67 will come in a subsequent commit.
=> [travis] Add Boost 1.67.0 to Travis image

appveyor.yml, tools/ci-scripts/windows/ConvertTo-MsvcVersion.ps1, tools/ci-scripts/windows/Get-BoostLocation.ps1, tools/ci-scripts/windows/Install-Boost.ps1
The AppVeyor builder images contain some versions of Boost, but not all
the versions that Bond supports for all the compilers that it supports.
This commit:
* Switches to a minimum Boost of 1.61, the minimum supported version as
of this commit.
* Adds a script to easily find the pre-installed Boost library.
* Adds a script to install a given version of Boost from NuGet.org
packages.
* Updates the AppVeyor build to install missing versions of Boost from
NuGet.org.
* Refactors the AppVeyor build to base the MSVC compiler off of the
BOND_VS_VERSION or the APPVEYOR_BUILD_WORKER_IMAGE variable, which
should set us up to add MSVC 2017 to the build later.
This is the AppVeyor side of https://github.com/Microsoft/bond/issues/771
=> [appveyor] Use Boost from NuGet packages if needed

cpp/inc/bond/protocol/simple_json_writer.h
Avoid any issues with default initialization.
=> [c++] Initialize SimpleJsonWriter._count to 0

cpp/inc/bond/protocol/detail/rapidjson_helper.h, cpp/inc/bond/protocol/simple_json_reader.h, cpp/test/core/json_tests.cpp
A SimpleJsonReader either has an input buffer and an associated stream
or it is a child of some other SimpleJsonReader that will use its
parent's already parsed document. This logic is now more explicit:
* A SimpleJsonReader now either has an input stream XOR a parent
pointer. This logic is implemented in the helper StreamHolder class.
* detail::RapidJsonInputStream now owns its input buffer instead of
having a reference to its input buffer.
* Before, when child SimpleJsonReader instances had their own
detail::RapidJsonInputStream instances, we needed to be able to
make cheap copies of detail::RapidJsonInputStream. But, the
children didn't actually use their stream except to sometimes make
a deep copy. Since they now just have a pointer to their parent
which can be used to make a deep …
=> [c++] Use a "variant" for SimpleJsonReader state

compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs, compiler/tests/generated/generic_service_grpc.h, compiler/tests/generated/service_attributes_grpc.h, compiler/tests/generated/service_grpc.h, cpp/inc/bond/ext/grpc/client_callback.h, cpp/inc/bond/ext/grpc/detail/service.h, cpp/inc/bond/ext/grpc/detail/service_call_data.h, cpp/inc/bond/ext/grpc/unary_call.h, cpp/test/grpc/service_attributes.cpp, cpp/test/grpc/wait_callback.cpp
The change avoids the explicit call to `service_unary_call_data::queue_receive` in the generated code.
=> [c++ grpc] Simplify service_unary_call_data

CHANGELOG.md, cpp/inc/bond/core/box.h, cpp/test/core/basic_tests.cpp
Fixes the bug that makes the following fail to compile:
```cpp
const int x = 1;
bond::Box<int> b = bond::make_box(x);
```
=> [c++] Fix make_box for const T&

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cpp/Grpc_h.hs, compiler/tests/generated/generic_service_grpc.h, compiler/tests/generated/service_attributes_grpc.h, compiler/tests/generated/service_grpc.h, cpp/inc/bond/ext/grpc/client_callback.h, cpp/inc/bond/ext/grpc/detail/client_call_data.h, cpp/inc/bond/ext/grpc/wait_callback.h, cpp/test/grpc/wait_callback.cpp
This change removes the unnecessary `std::shared_ptr` wrapper when passing `unary_call_result<Response>` to a client callback.
Built on top of #882.
=> [c++ grpc] Use plain unary_call_result

cs/test/grpc/packages.config, examples/cs/grpc/shared-types-assembly/client/packages.config, examples/cs/grpc/shared-types-assembly/server/packages.config
When we converted to the SDK-based project format in commit 3c7bdb9738,
we moved our package references inside the .csproj files, so we can
delete the older packages.config files that were left over.
=> [c#] Remove unused packages.config files

cpp/test/grpc/io_manager.cpp
The global memory leak [has been fixed](https://github.com/grpc/grpc/commit/1a956bcd3274fb9135d63101b803c00015f3f2af) in grpc 1.12.0.
=> [c++ grpc] Remove disabled memory leak detection

cpp/inc/bond/ext/grpc/unary_call.h
Switch to using the base's explicit full name in a `using` statement to
pull in ctor to avoid a MSVC 14 bug.
=> [c++ grpc] Work around MSVC 14 base name bug

compiler/bond.cabal, compiler/stack.yaml
Cabal now checks that pacakges do not have -Wall -Werror enabled when
creating sdist tarballs for uploading to Hackage:
> Package check reported the following errors:
> 'ghc-options: -Wall -Werror' makes the package very easy to break with
> future GHC versions because new GHC versions often add new warnings.
> Use just 'ghc-options: -Wall' instead. Alternatively, if you want to
> use this, make it conditional based on a Cabal configuration
> flag (with 'manual: True' and 'default: False') and enable that flag
> during development.
This places those options behind a flag.
=> [gbc] Fix -Wall -Werror packaging warning

compiler/CMakeLists.txt
Removes install(FILES) for bash completion file in favor of a install(CODE). It runs bash to detech if directory /etc/bash_completion.d is writable by the user installing. If it is, it will cp and chmod the gbc completion file.
It assumes that the user has bash but that is highly likely to be true if the machine contains directory /etc/bash_completion.d.
=> Issue #932. Fixes Linux non-root install failure

CHANGELOG.md, cpp/inc/bond/core/blob.h, cpp/test/core/blob_tests.cpp
Pull request for issue #934. The tests are probably overkill, I can remove them if you want. But they showed that
`
blob& operator=(blob&& that) = default;
`
would copy the internal buffer instead of moving it, so I chose the swap implementation.
=> Implement move assignment for the bond::blob type

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cs/Grpc_cs.hs, compiler/tests/generated/generic_service_grpc.cs, compiler/tests/generated/service_attributes_grpc.cs, compiler/tests/generated/service_grpc.cs, compiler/tests/generated/streaming_grpc.cs
New feature of Interceptor was added to grpc, and client side
interceptor relies on CallInvoker to work. 
Protobuf has already added the constructor for C#.
See
[L12-csharp-interceptors](https://github.com/grpc/proposal/blob/master/L12-csharp-interceptors.md)
and
[discussion](https://github.com/grpc/grpc/issues/11646#issuecomment-312799633).
Fix #950
=> [C# Grpc] Support initializing a grpc service client with a CallInvoker instance.

cpp/inc/bond/core/nullable.h
It is fine for `destroy`, but for `construct` is technically UB to use `addressof(*p)` as `p` does not reference an object that was constructed. See [P0653R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0653r2.html) and `std::to_address` in C++2a. This is existing practice in libc++ (`__to_raw_pointer`), libstdc++ (`__to_address`), and Boost (`boost::to_address` since Boost 1.67).
=> Avoid addressof(*p) when p doesn't alias an object

compiler/bond.cabal
- Relax dependency on `process` package to support newer version of
`base`.
- Restrict dependency on `megaparsec` to less than version 7 which has
incompatible APIs.
=> Update bond.cabal constraints

.travis.yml
The bondciimages.azurecr.io has been configured for anonymous read-only
access, so the `docker login` step is no longer needed.
=> Remove docker login from Travis build

CHANGELOG.md, CONTRIBUTING.md, README.md, appveyor.yml, compiler/bond.cabal, cs/build/nuget/cps/README.md, cs/nuget/bond.compiler.csharp.nuspec, cs/nuget/bond.compiler.nuspec, cs/nuget/bond.core.csharp.nuspec, cs/nuget/bond.csharp.nuspec, cs/nuget/bond.grpc.csharp.nuspec, cs/nuget/bond.runtime.csharp.nuspec, cs/nuget/readme.txt, doc/src/bond_cpp.md, doc/src/bond_cs.md, doc/src/bond_java.md, doc/src/bond_over_grpc.md, doc/src/bond_py.md, doc/src/why_bond.md, tools/ci-scripts/linux/image-builder/README.md
Microsoft has renamed its GitHub organization from "Microsoft" to
"microsoft". This commit fixes various paths, as not all tools are able
to follow the Microsoft -> microsoft redirects that are in place.
These replacements were made with the following script:
for f in $(grep -l -r -e 'github.com/Microsoft' -e 'Microsoft/bond' -e 'Microsoft.github.io' *); do
sed -i -e 's~github.com/Microsoft~github.com/microsoft~g; s~Microsoft/bond~microsoft/bond~g;s~Microsoft.github.io~microsoft.github.io~g' "$f"
done
=> Switch to microsoft/bond casing

tools/ci-scripts/linux/image-cleanup/collector/acr.py
The old syntax for deleting by a manifest no longer works with newer
versions of the az CLI tool. This switches to the newer `--image
repository@manifest` syntax.
This should fix the [image cleanup job failures](https://dev.azure.com/msazure/One/_build?definitionId=21361) that we've been seeing.
=> Use new `az acr repository delete --image` syntax

.travis.yml, tools/ci-scripts/linux/image-builder/README.md
Updates the Linux CI build image to build-22756092 which was built
against commit 62da781cb2.
Due to a combination of two bugs in the clean up script, we've lost all
the images except for the one reference by the 8.1.0 tag,
build-13234037.
1. The clean up script was supposed to be configured to retain images
reference by all tags. However, it was only retaining the image
reference by the most recent tag. This was fixed by using `git
rev-list --tags --simplify-by-decoration --dense` instead of `git
rev-list --tags -n 1`
1. The clean up script was configured to retain images reference by the
last two weeks of commits. There has been a period without any
commits in two weeks, so the images reference by the current tip of
master were collected. This has been fixed by adding the results of …
=> Refresh Linux CI build image

CHANGELOG.md, cpp/inc/bond/core/maybe.h
The move of the maybe::operator== from the two variants to the common
base maybe_common causes an ambiguity with the allocator operator==
from libstdc++ in GCC 9.1. Moving them back to the variants fixes this
issue.
More detailed description:
When compiling Bond 8.1 code with gcc 9.1.0 / the current libstdc++, I get an ambiguous overload error for the
friend bool operator==(const maybe_common& lhs, const maybe_common& rhs)
from maybe.h line 195. The ambiguous other operator being
operator==(const allocator<_T1>&, const allocator<_T2>&)
from allocator.h:168 (and another similar one from new_allocator.h).
Moving the shared operator== implementation from maybe_common to both of the maybe variants fixes the issue, but I'm not sure if this is the best approach. See the attached patch. I'm also …
=> Move maybe::operator== back from maybe_common to maybe implementations

CHANGELOG.md, cpp/inc/bond/core/protocol.h
Adds a spot suppression for MSVC warning C4296: '<' : expression is
always false. MSVC's "always constant" warnings tend to trigger on
tempalted code based on the specific instantiation's values,
disregarding that the template itself it not always constant.
Fixes https://github.com/microsoft/bond/issues/981
=> Suppress MSVC warning '<': expression always false

cpp/inc/bond/core/detail/mpl.h
Addresses issue https://github.com/microsoft/bond/issues/984
All unit tests pass.
=> Fixes mpl.h compilation error in Clang raised by -Wreturn-std-move

cs/src/core/io/safe/OutputBuffer.cs
Current Grow implementation works inefficiently for
buffer sizes larger than 2/3 of int.MaxValue. After that size,
each grow will result in small incremental resize to the next
required count, copying huge amounts of data each time.
=> Improve OutputBuffer Grow method for large buffers

tools/ci-scripts/linux/image-builder/Dockerfile
Current versions of stack appear to need happy installed ahead of time
to use the happy package.
=> Install happy in Travis CI image

.travis.yml
The Travis CI image now includes happy pre-installed, as the Haskell LTS we
use needs happy pre-installed.
This image was built from commit dd105d96b64884c1297286a0023d726db06ec1a2.
=> Refresh Travis CI build image

.travis.yml
Switch to a Travis build with ghc pre-installed that was built 
from commit 5b3a783ce17a942afcb12f586c517ca3278398c2.
=> Use Travis build image with ghc pre-installed

CHANGELOG.md, cs/nuget/bond.core.csharp.nuspec, cs/src/io/IO.csproj, cs/src/io/unsafe/StreamCloning.cs, doc/src/bond_cs.md
.NET 4.6 implements `MemoryStream.TryGetBuffer()`, so we can use that to
clone streams instead of finding a private method via reflection.
This requires adding .NET 4.6 as one of the target frameworks for
Bond.IO.dll, since NuGet will pick the .NET 4.5 version of Bond.IO.dll
over the .NET Standard 1.3 one when a consuming project itself targets
.NET Framework 4.6+.
=> Use MemoryStream.TryGetBuffer to clone streams on .NET 4.6

compiler/CMakeLists.txt
The stack `--split-obj` option is currently not working on Windows. When
it is enabled, builds fail with errors like:
.stack-work\dist\e626a42b\build\Data\Orphans_o_split: getDirectoryContents:findFirstFile: does not exist (The system cannot find the path specified.)
`--split-obj` is a preview feature, so this isn't unexpected.
For now, removing this flag from the MinSizeRel configuration.
=> Remove non-functional --split-obj from gbc build

cpp/inc/bond/stream/output_buffer.h
Closes #1018
On the first call to Write, std::memcpy() is called with a nullptr destination and a size of zero. While this should be safe in practice, it is undefined behaviour: https://en.cppreference.com/w/cpp/string/byte/memcpy
=> avoid undefined behaviour of std::memcpy() on initial write to buffer

CHANGELOG.md, cmake/Config.cmake, cpp/inc/bond/core/config.h, cpp/inc/bond/core/detail/visit_any.h
`try_visit_any` uses `std::result_of_t` which is deprecated in C++17. This PR replaces `std::result_of_t` by `std::invoke_result_t` so we can compile in C++ 17 mode without disabling any warnings.
Fixes #1007
=> Remove std::result_of_t deprecated in C++17

tools/ci-scripts/windows/ConvertTo-MsvcVersion.ps1, tools/ci-scripts/windows/Get-BoostLocation.ps1, tools/ci-scripts/windows/Install-Boost.ps1
Update AppVeyor to know about VS 2019.
Fixes #1038
=> Update AppVeyor to know about VS 2019

CHANGELOG.md, cpp/inc/bond/core/schema.h, cpp/test/compat/core/serialization.cpp, cpp/test/core/apply_tests.cpp, cpp/test/core/exception_tests.cpp, cpp/test/core/marshal.cpp, cpp/test/core/pass_through.cpp, cpp/test/core/required_fields_tests.cpp, cpp/test/core/unit_test_util.h, examples/cpp/core/runtime_binding/runtime_binding.cpp
boost/bind.hpp is deprecated and recommends using boost/bind/bind.hpp instead, see: https://github.com/boostorg/bind/blob/develop/include/boost/bind.hpp
=> Use non-deprecated bind/bind.hpp header

CHANGELOG.md, cs/build/nuget/Common.targets, cs/test/grpc/services2.bond
When a project has multiple .bond files in `@BondCodegen` and specified
`--grpc` in `$BondOptions`, the C# code generation targets erroneously
added the generated files to the `@Compile` item multiple times.
This was caused because the `@_BondGen_Grpc_BondOptions` item
incorrectly used `%(BondCodegen.Identity)` when populating
`%DependentUpon`. Since `@_BondGen_Grpc_BondOptions` and `@BondCodegen`
are different items, this multiplied them together. A mapping was
intended instead, so the fix is to use
`%_BondGen_Grpc_BondOptions.Identity`. (This was likely a copy/paste bug
when `--grpc` support was added to the targets.)
Fixes https://github.com/microsoft/bond/issues/1050
=> [c#] Fix duplicate Compile item error with --grpc

CMakeLists.txt
Projects that import Bond using add_subdirectory pointed at a git submodule may want to set `BOND_ENABLE_GRPC` and `BOND_FIND_RAPIDJSON` through top-level CMakeLists.txt. However, this doesn't work without creating an identical option() in the importing project. Enabling CMP0077 in CMake 3.13+ changes the behavior of option() to allow importing projects to set default values for the variables without touching the cache.
Documentation for CMP0077: https://cmake.org/cmake/help/latest/policy/CMP0077.html
=> Conditionally enable CMake policy CMP0077

cs/build/nuget/Common.targets
The MSBuild target `BondCompileCs` depends on the target `BondCodegenCs`
to populate the `@_BondCodegenWithDefaultOptions` item. It is currently
always running after `BondCompileCs` since it comes after that target in
the .targets file. Adding an explicit `DependsOnTargets="BondCodegenCs"`
is more robust.
=> [c#] Be explicit about codegen target dependencies

cs/.gitignore, examples/cs/.gitignore
Also, synchronize the .gitignore files used for the C# source tree and
the examples tree.
=> [c#] Ignore msbuild.binlog files

cs/nuget/bond.compiler.csharp.nuspec, cs/nuget/bond.compiler.nuspec, cs/nuget/bond.core.csharp.nuspec, cs/nuget/bond.csharp.nuspec, cs/nuget/bond.grpc.csharp.nuspec, cs/nuget/bond.runtime.csharp.nuspec
The nuspec elements `iconUrl` and `licenseUrl` are deprecated in favor of
the `icon` and `license` elements.
This commit replaces `licenseUrl` with `license` (The two cannot
co-exist.) and adds `icon`. (The current recommendation is to have both
for compatibility.)
The `icon` element requires that the icon file be in the package, so the
packages all now use the repository root as the base for their files and
include the icon .png.
=> [c#] Add new style license and icon to NuGet pkgs.

tools/ci-scripts/linux/build_cpp-grpc-master.zsh
Sometimes gRPC adds new submodule dependencies, so we need to pass the
`--init` flag to `git submodule update` so that new submodules are
initialized, lest the build fail.
=> [c++ grpc] Pass --init to update gRPC submodules

CHANGELOG.md, cs/src/core/protocols/CompactBinary.cs, cs/test/core/StreamTests.cs
This pull request attempts to fix a regression introduced in [b0fd4a1](https://github.com/microsoft/bond/commit/b0fd4a15a7cae946dd2855122559ca59cc34dbea#diff-9534daaa1fb3d4776494b25c8bba3939L212). 
The previous code for `CompactBinary.WriteStructBegin` would not access the `output.Position` in the Release build configuration whereas the changes introduced caused it to now be accessed regardless of configuration. This can cause exceptions in scenarios where the `Stream` is not seekable.
The fix moves the computation of the length back into the arguments of the function which ensures it will not be executed outside of the Debug build configuration.
=> [c#] Move Position Computation Into PushLengthCheck Args

examples/cpp/core/attributes/attributes.cpp
Resolves a warning emitted by G++ 9.3.0
=> [c++] Catch exception by ref in attribute example

NuGet.Config
Add an explicit NuGet.Config file that configures NuGet.org as Bond's
package source. This helps avoid an error restoring packages when Bond
is a submodule of a repo that uses a private package feed.
=> [c#] Add explicit NuGet.Config with sources

CHANGELOG.md, python/inc/bond/python/converters.h
`std::ptr_fun` is deprecated in C++11 and removed in C++17.
Replace its one use with a lambda.
Fixes https://github.com/microsoft/bond/issues/1080
=> [c++] [python] Replace deprecated std::ptr_fun

doc/src/bond_cs.md
A number of recent support requests (for example, [issue
\#1083](https://github.com/microsoft/bond/issues/1083)) have been
resolved by using `inlineNested: false` when creating
`Serializer`/`Deserializer` instances.
Add details about `inlineNested` to the C# performance guidance.
=> [cs] Mention inlineNested in perf guidance

appveyor.yml
The `.github/` directory contains GitHub Actions workflows, which do not
contribute to the AppVeyor builds.
Do not trigger AppVeyor build on .github/ changes.
=> [ci] Do not trigger AppVeyor build on .github/ changes

tools/ci-scripts/linux/image-cleanup/collect_images.py, tools/ci-scripts/linux/image-cleanup/collector/live_images.py
The new GitHub Action workflows also use the CI build Docker images.
Add the current two workflow YAML files as additional roots for Docker
images. Revise wording to be more agnostic of the CI system.
=> [ci] Add GitHub Action workflow files as image roots

doc/src/bond_cpp.md
The docs extensively mention Compact Binary v2, however there are no
clear instructions on how to enable it unless you carefully read the
`CompactBinaryReader` and `CompactBinaryWriter` constructor docs.
I spent quite some time trying to figure it out until @chwarr pointed me
in the right direction. Hopefully the next reader finds it easier!
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> [doc] Explain how to enable Compact Binary v2 on C++

cpp/inc/bond/protocol/compact_binary.h
In particular:
- ID bits consists of big endian unsigned integers
- int8 uses two's complement
- Just to make it super clear, "variable encoding" of integers refers to
LEB128
- Real numbers use IEEE 764
- Enum constants are int32
I had to run various experiments to find these things out and they might
be helpful for the next reader.
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> [c++] Clarify some details of the Compact Binary encoding

doc/src/compiler.md
The link on the compilers page (http://microsoft.github.io/bond/manual/compiler.html#type-aliases) to the custom type mapping documentation is dead as it doesn't point to the correct page. Here's a PR to fix it.
=> [doc] Fix dead link in compilers page to custom type mapping documentation

appveyor.yml
Attempt to fix doc build issue #1086 by doing a manual refresh env in Appveyor script after installing Doxygen.
In my local testing when I didn't do refreshenv, doxygen was not found and CMake didn't generate the `documentation` target.
=> Add Doxygen path to build path of Doc step in CI pipeline

appveyor.yml
We're having trouble using the Remove-Item/Copy-Item pair to synchronize
the documentation build output with the gh-pages branch.
Switch to robocopy, which has a /MIR (mirror) mode as well as
/XD (exclude directory).
Test $LASTEXITCODE instead of $?. Due to how PowerShell handles the
error stream, $? is set to false if the process writes to stderr, even
if the process exits with 0.
=> [doc] Switch to robocopy to mirror doc build output

.github/workflows/linux.yml
The GitHub workflow runs even if the changes don't affect the Linux
build.
Skip workflow runs for commits that don't affect the Linux build.
Negative path patterns are used in instead of paths-ignore: if anything
in paths-ignore matches, the workflow will be skipped, which is too
aggressive. Instead, the workflow should be skipped if the change solely
affects ignored files.
=> [ci] Skip GitHub workflow if changes don't affect the build

cmake/Config.cmake
I cannot compile Microsoft Bond on macOS Big Sur 11.2.2 and Xcode 12.4
with Apple clang version 12.0.0 (clang-1200.0.32.29) and Boost 1.75.0
because of this flag:
```
In file included from /usr/local/include/boost/locale.hpp:24:
/usr/local/include/boost/locale/util.hpp:203:59: error: 'auto_ptr<boost::locale::util::base_converter>' is deprecated [-Werror,-Wdeprecated-declarations]
std::locale create_codecvt(std::locale const &in,std::auto_ptr<base_converter> cvt,character_facet_type type);
```
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>
=> [c++] Set -Wno-deprecated-declarations for AppleClang too

appveyor.yml
During the doc build, if there are no changes, `git commit` [exits with
1 and the build fails][1].
Don't test exit code of `git commit`. The subsequent `git push` will
exit with 0 even if there is nothing to do, so subsequent tests will see
a $LASTEXITCODE of 0.
[1]: https://ci.appveyor.com/project/MicrosoftBond/bond/branch/master/job/j8ujo6s6pb59an50
=> [doc] Do not fail build when there are no changes

CHANGELOG.md, cs/build/nuget/Common.props, cs/cs.sln, cs/test/codegen/default-ignore-output/ConsumeCodegen.cs, cs/test/codegen/default-ignore-output/README.md, cs/test/codegen/default-ignore-output/bin/should-not-be-compiled.bond, cs/test/codegen/default-ignore-output/default-ignore-output.csproj, cs/test/codegen/default-ignore-output/obj/debug/netstandard1.0/should-not-be-compiled.bond, cs/test/codegen/default-ignore-output/obj/retail/netstandard1.0/should-not-be-compiled.bond, cs/test/codegen/default-ignore-output/obj/should-not-be-compiled.bond, cs/test/codegen/default-ignore-output/simple.bond
Bond's implicit code generation includes any .bond files in the
project's output directories (e.g., `bin/` or
`obj/debug/netstandard1.0`). Some projects that copied .bond files into
their output directories would then encounter codegen issues when gbc
was run on these .bond files implicitly, particularly during incremental
builds.
Omit any .bond files that match `$(DefaultItemExcludes)` or
`$(DefaultExcludesInProjectFolder)` from implicit codegen.
Add a regression codegen test.
This behavior now matches what the .NET SDK does for .cs files.
=> [c#] Exclude files in output dir from implicit codegen

CHANGELOG.md, cpp/inc/bond/protocol/encoding.h
Some users are reporting that they are receiving error "C3861:
'GenericWriteVariableUnsigned': identifier not found" when building.
I think this happens when custom streams that _do not_ have their own
`WriteVariableUnsigned` member function.
Add a forward declaration of `GenericWriteVariableUnsigned`.
Fixes https://github.com/microsoft/bond/issues/1115
=> [c++] Forward declare GenericWriteVariableUnsigned

CHANGELOG.md, cpp/inc/bond/core/bond_fwd.h, cpp/inc/bond/core/detail/omit_default.h, cpp/inc/bond/core/protocol.h, cpp/inc/bond/core/traits.h, cpp/inc/bond/core/value.h
Repro:
```C++
#include <bond/core/reflection.h> // Must be the first include for repro
```
Errors from `omit_default.h`:
```
bond\cpp\inc\bond\core\detail\omit_default.h(29,18): error C2027: use of undefined type 'bond::value'
bond\cpp\inc\bond\core\detail\omit_default.h(36,29): error C2065: 'is_basic_type': undeclared identifier
bond\cpp\inc\bond\core\detail\omit_default.h(37,1): error C2588: '::!is_string_type': illegal global finalizer
bond\cpp\inc\bond\core\detail\omit_default.h(48,27): error C2065: 'is_type_alias': undeclared identifier
bond\cpp\inc\bond\core\detail\omit_default.h(68,27): error C2065: 'is_wstring': undeclared identifier
bond\cpp\inc\bond\core\detail\omit_default.h(79,27): error C2065: 'is_container': undeclared identifier …
```
=> [c++] Fixed missing include directives

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cpp/ApplyOverloads.hs, compiler/tests/generated/apply/basic_types_apply.cpp, compiler/tests/generated/apply/basic_types_apply.h, cpp/inc/bond/core/apply.h, cpp/inc/bond/core/bond_fwd.h, cpp/inc/bond/core/detail/protocol_visitors.h, cpp/inc/bond/core/reflection.h, cpp/inc/bond/core/schema.h, cpp/inc/bond/core/value.h, cpp/test/core/apply_tests.cpp
Sometimes it is necessary to apply a custom transform to a schema, rather than an object or a serialized data. One such use case is the `bond::InitSchemaDef` which is applied to a compile-time schema in order to generate a corresponding runtime one.
One way to achieve that is to apply it to a dummy object. That is not always possible or convenient to do, like in this case,, and we choose to rely on some undefined behavior and fake objects.
There is no canonical way of doing the same for runtime schema, and instead a manual traversal of `bond::SchemaDef` structure is needed, or more tricky ways of using one of the existing protocol readers.
This change is adding two more overloads to `bond::Apply` that would make such transformation possible in a canonical and legal way.
=> [c++] Add an ability to apply transform to a schema

CHANGELOG.md
The ability to apply a transform without an object is new functionality.
Indicate this via a minor version bump.
=> Indicate C++ minor version bump needed

tools/ci-scripts/linux/image-builder/Dockerfile
The Mono apt source has started redirecting to https. The CI image
Dockerfile wasn't installing the needed components to have apt connect
over https.
Install the missing components. Use an explicit https source instead of
relying on the redirection.
=> [c#] Use https apt source to fetch mono

CHANGELOG.md, cs/build/nuget/Common.targets
The "Duplicate BondCodegen items were included" error message says that
the `$(EnableDefaultCompileItems)` property can be set to false to stop
automatic inclusion. The automatic inclusion behavior is conditioned on
the `$(EnableDefaultItems)` property, not
`$(EnableDefaultCompileItems)`.
Revise the error message to mention `$(EnableDefaultItems)`.
Fixes https://github.com/microsoft/bond/issues/1110
=> [c#] Refer to $(EnableDefaultItems) in dup codegen error

doc/src/bond_cpp.md, doc/src/bond_cs.md, doc/src/compiler.md
The schema evolution documentation refers to "field ordinals", which is
terminology that may not be familiar to all users of Bond.
Refer to "field ordinals" as "field ordinals/ids" in schemea evolution
and compiler documentation.
Add minor clarification and emphasize around when default values are
optional or required.
=> Use "field id" phrasing in schema evolution

README.md
CMake should be invoked to generate build script before running make, or there is nothing to make int he create build directory.
=> Fix missing cmake call in build instruction for Linux and MacOS

appveyor.yml
CI builds are failing with linker errors trying to install happy. This workaround no longer appears to be needed.
Remove the manual install step.
=> [ci] Revert happy install workaround

CHANGELOG.md, compiler/src/Language/Bond/Codegen/Cs/Util.hs, compiler/tests/TestMain.hs, compiler/tests/generated/collection-interfaces/immutable_collections_types.cs, compiler/tests/generated/immutable_collections_types.cs, compiler/tests/schema/immutable_collections.bond, cs/cs.sln, cs/nuget/bond.csharp.test.csproj, cs/src/core/Comparer.cs, cs/src/core/expressions/DeserializerTransform.cs, cs/test/core/Core.csproj, cs/test/core/ImmutableCollections.bond, cs/test/core/SerializationTests.cs, cs/test/core/UnitTest.bond, cs/test/coreNS10/CoreNS10.csproj, doc/src/bond_cs.md, examples/cs/core/immutable_collections/Program.cs, examples/cs/core/immutable_collections/immutable_collections.csproj, examples/cs/core/immutable_collections/schema.bond
Closes #1159
Adds proper support for immutable collections as laid out in the issue description. Implemented this in a way such that the Bond C# package doesn't actually depend on System.Collections.Immutable, roughly following how it was done [in Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ImmutableCollectionsUtils.cs). 
The collections are constructed using the builders, which performs a lot better doing bulk operations.
The change to the codegen in Haskell is small, but since I don't have much experience, any suggestions to make it more idiomatic are welcome. 
Added unit tests both for the compiler and for [de]serialization in C#.
=> [c#] support for system.collections.immutable collections

cpp/inc/bond/core/detail/sdl.h
I work on MSVC's STL, and we'd like you to stop using one of our old non-Standard extensions, as we're working towards eventually removing it.
In VS 2005, MSVC's non-Standard extension `stdext::checked_array_iterator` was added to provide guaranteed bounds checking. At the same time, MSVC began emitting Microsoft "deprecation" warnings for using raw pointers as output iterators.
In VS 2017 15.8 (`_MSC_VER` `1915`; see our handy [decoder table][]), we stopped emitting those Microsoft "deprecation" warnings for using raw pointers as output iterators. Those warnings were incredibly annoying since they warned about perfectly correct, Standard-conforming code, and led users to generally disregard and silence such warnings. Also, the library was never the right place to implement them because …
=> Avoid `stdext::checked_array_iterator` for modern MSVC

CHANGELOG.md, examples/cpp/core/multiprecision/multiprecision.cpp, examples/cpp/core/multiprecision/multiprecision.h, tools/ci-scripts/linux/image-builder/build_boosts.zsh, tools/ci-scripts/windows/Get-BoostLocation.ps1, tools/ci-scripts/windows/Install-Boost.ps1
This adds Boost 1.83 and MSVC 14.3 as options to C++ CI scripts. Additionally, the `multiprecision` build error due to use of deprecated random number generator is fixed.
=> Add support for Boost 1.83

CHANGELOG.md, README.md
The Bond open-source project will be ending development on March 31, 2025.
Add notes about this to the README and the CHANGELOG.
=> Add notes about March 2025 project shutdown
